/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.flipkart.api.seller.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.flipkart.api.seller.client.model.BulkConfirmedItem;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * BulkActionProgressResponse
 */

public class BulkActionProgressResponse {
  @JsonProperty("confirmedCount")
  private Integer confirmedCount = null;

  @JsonProperty("errorCount")
  private Integer errorCount = null;

  @JsonProperty("completedCount")
  private Integer completedCount = null;

  @JsonProperty("processingCount")
  private Integer processingCount = null;

  @JsonProperty("orderItemDetails")
  private List<BulkConfirmedItem> orderItemDetails = null;

  @JsonProperty("complete")
  private Boolean complete = null;

  public BulkActionProgressResponse confirmedCount(Integer confirmedCount) {
    this.confirmedCount = confirmedCount;
    return this;
  }

   /**
   * Get confirmedCount
   * @return confirmedCount
  **/
  @ApiModelProperty(value = "")
  public Integer getConfirmedCount() {
    return confirmedCount;
  }

  public void setConfirmedCount(Integer confirmedCount) {
    this.confirmedCount = confirmedCount;
  }

  public BulkActionProgressResponse errorCount(Integer errorCount) {
    this.errorCount = errorCount;
    return this;
  }

   /**
   * Get errorCount
   * @return errorCount
  **/
  @ApiModelProperty(value = "")
  public Integer getErrorCount() {
    return errorCount;
  }

  public void setErrorCount(Integer errorCount) {
    this.errorCount = errorCount;
  }

  public BulkActionProgressResponse completedCount(Integer completedCount) {
    this.completedCount = completedCount;
    return this;
  }

   /**
   * Get completedCount
   * @return completedCount
  **/
  @ApiModelProperty(value = "")
  public Integer getCompletedCount() {
    return completedCount;
  }

  public void setCompletedCount(Integer completedCount) {
    this.completedCount = completedCount;
  }

  public BulkActionProgressResponse processingCount(Integer processingCount) {
    this.processingCount = processingCount;
    return this;
  }

   /**
   * Get processingCount
   * @return processingCount
  **/
  @ApiModelProperty(value = "")
  public Integer getProcessingCount() {
    return processingCount;
  }

  public void setProcessingCount(Integer processingCount) {
    this.processingCount = processingCount;
  }

  public BulkActionProgressResponse orderItemDetails(List<BulkConfirmedItem> orderItemDetails) {
    this.orderItemDetails = orderItemDetails;
    return this;
  }

  public BulkActionProgressResponse addOrderItemDetailsItem(BulkConfirmedItem orderItemDetailsItem) {
    if (this.orderItemDetails == null) {
      this.orderItemDetails = new ArrayList<BulkConfirmedItem>();
    }
    this.orderItemDetails.add(orderItemDetailsItem);
    return this;
  }

   /**
   * Get orderItemDetails
   * @return orderItemDetails
  **/
  @ApiModelProperty(value = "")
  public List<BulkConfirmedItem> getOrderItemDetails() {
    return orderItemDetails;
  }

  public void setOrderItemDetails(List<BulkConfirmedItem> orderItemDetails) {
    this.orderItemDetails = orderItemDetails;
  }

  public BulkActionProgressResponse complete(Boolean complete) {
    this.complete = complete;
    return this;
  }

   /**
   * Get complete
   * @return complete
  **/
  @ApiModelProperty(value = "")
  public Boolean isComplete() {
    return complete;
  }

  public void setComplete(Boolean complete) {
    this.complete = complete;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BulkActionProgressResponse bulkActionProgressResponse = (BulkActionProgressResponse) o;
    return Objects.equals(this.confirmedCount, bulkActionProgressResponse.confirmedCount) &&
        Objects.equals(this.errorCount, bulkActionProgressResponse.errorCount) &&
        Objects.equals(this.completedCount, bulkActionProgressResponse.completedCount) &&
        Objects.equals(this.processingCount, bulkActionProgressResponse.processingCount) &&
        Objects.equals(this.orderItemDetails, bulkActionProgressResponse.orderItemDetails) &&
        Objects.equals(this.complete, bulkActionProgressResponse.complete);
  }

  @Override
  public int hashCode() {
    return Objects.hash(confirmedCount, errorCount, completedCount, processingCount, orderItemDetails, complete);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BulkActionProgressResponse {\n");
    
    sb.append("    confirmedCount: ").append(toIndentedString(confirmedCount)).append("\n");
    sb.append("    errorCount: ").append(toIndentedString(errorCount)).append("\n");
    sb.append("    completedCount: ").append(toIndentedString(completedCount)).append("\n");
    sb.append("    processingCount: ").append(toIndentedString(processingCount)).append("\n");
    sb.append("    orderItemDetails: ").append(toIndentedString(orderItemDetails)).append("\n");
    sb.append("    complete: ").append(toIndentedString(complete)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

