/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.flipkart.api.seller.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.flipkart.api.seller.client.model.BulkConfirmItem;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * BulkConfirmResponseV2
 */

public class BulkConfirmResponseV2 {
  @JsonProperty("requestId")
  private String requestId = null;

  @JsonProperty("orderItems")
  private List<BulkConfirmItem> orderItems = null;

  public BulkConfirmResponseV2 requestId(String requestId) {
    this.requestId = requestId;
    return this;
  }

   /**
   * Get requestId
   * @return requestId
  **/
  @ApiModelProperty(value = "")
  public String getRequestId() {
    return requestId;
  }

  public void setRequestId(String requestId) {
    this.requestId = requestId;
  }

  public BulkConfirmResponseV2 orderItems(List<BulkConfirmItem> orderItems) {
    this.orderItems = orderItems;
    return this;
  }

  public BulkConfirmResponseV2 addOrderItemsItem(BulkConfirmItem orderItemsItem) {
    if (this.orderItems == null) {
      this.orderItems = new ArrayList<BulkConfirmItem>();
    }
    this.orderItems.add(orderItemsItem);
    return this;
  }

   /**
   * Get orderItems
   * @return orderItems
  **/
  @ApiModelProperty(value = "")
  public List<BulkConfirmItem> getOrderItems() {
    return orderItems;
  }

  public void setOrderItems(List<BulkConfirmItem> orderItems) {
    this.orderItems = orderItems;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BulkConfirmResponseV2 bulkConfirmResponseV2 = (BulkConfirmResponseV2) o;
    return Objects.equals(this.requestId, bulkConfirmResponseV2.requestId) &&
        Objects.equals(this.orderItems, bulkConfirmResponseV2.orderItems);
  }

  @Override
  public int hashCode() {
    return Objects.hash(requestId, orderItems);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BulkConfirmResponseV2 {\n");
    
    sb.append("    requestId: ").append(toIndentedString(requestId)).append("\n");
    sb.append("    orderItems: ").append(toIndentedString(orderItems)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

