/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.flipkart.api.seller.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * CancelShipment
 */

public class CancelShipment {
  @JsonProperty("shipmentId")
  private String shipmentId = null;

  @JsonProperty("reason")
  private String reason = null;

  @JsonProperty("locationId")
  private String locationId = null;

  @JsonProperty("cancellationGroupIds")
  private List<String> cancellationGroupIds = null;

  public CancelShipment shipmentId(String shipmentId) {
    this.shipmentId = shipmentId;
    return this;
  }

   /**
   * Get shipmentId
   * @return shipmentId
  **/
  @ApiModelProperty(value = "")
  public String getShipmentId() {
    return shipmentId;
  }

  public void setShipmentId(String shipmentId) {
    this.shipmentId = shipmentId;
  }

  public CancelShipment reason(String reason) {
    this.reason = reason;
    return this;
  }

   /**
   * Get reason
   * @return reason
  **/
  @ApiModelProperty(value = "")
  public String getReason() {
    return reason;
  }

  public void setReason(String reason) {
    this.reason = reason;
  }

  public CancelShipment locationId(String locationId) {
    this.locationId = locationId;
    return this;
  }

   /**
   * Get locationId
   * @return locationId
  **/
  @ApiModelProperty(value = "")
  public String getLocationId() {
    return locationId;
  }

  public void setLocationId(String locationId) {
    this.locationId = locationId;
  }

  public CancelShipment cancellationGroupIds(List<String> cancellationGroupIds) {
    this.cancellationGroupIds = cancellationGroupIds;
    return this;
  }

  public CancelShipment addCancellationGroupIdsItem(String cancellationGroupIdsItem) {
    if (this.cancellationGroupIds == null) {
      this.cancellationGroupIds = new ArrayList<String>();
    }
    this.cancellationGroupIds.add(cancellationGroupIdsItem);
    return this;
  }

   /**
   * Get cancellationGroupIds
   * @return cancellationGroupIds
  **/
  @ApiModelProperty(value = "")
  public List<String> getCancellationGroupIds() {
    return cancellationGroupIds;
  }

  public void setCancellationGroupIds(List<String> cancellationGroupIds) {
    this.cancellationGroupIds = cancellationGroupIds;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CancelShipment cancelShipment = (CancelShipment) o;
    return Objects.equals(this.shipmentId, cancelShipment.shipmentId) &&
        Objects.equals(this.reason, cancelShipment.reason) &&
        Objects.equals(this.locationId, cancelShipment.locationId) &&
        Objects.equals(this.cancellationGroupIds, cancelShipment.cancellationGroupIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(shipmentId, reason, locationId, cancellationGroupIds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CancelShipment {\n");
    
    sb.append("    shipmentId: ").append(toIndentedString(shipmentId)).append("\n");
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("    locationId: ").append(toIndentedString(locationId)).append("\n");
    sb.append("    cancellationGroupIds: ").append(toIndentedString(cancellationGroupIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

