/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.flipkart.api.seller.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.LocalDate;

/**
 * ConfirmItemRow
 */

public class ConfirmItemRow {
  @JsonProperty("serialNumbers")
  private List<List<String>> serialNumbers = null;

  @JsonProperty("invoiceDate")
  private LocalDate invoiceDate = null;

  @JsonProperty("invoiceNumber")
  private String invoiceNumber = null;

  @JsonProperty("orderItemId")
  private String orderItemId = null;

  @JsonProperty("taxRate")
  private BigDecimal taxRate = null;

  @JsonProperty("quantity")
  private Integer quantity = null;

  public ConfirmItemRow serialNumbers(List<List<String>> serialNumbers) {
    this.serialNumbers = serialNumbers;
    return this;
  }

  public ConfirmItemRow addSerialNumbersItem(List<String> serialNumbersItem) {
    if (this.serialNumbers == null) {
      this.serialNumbers = new ArrayList<List<String>>();
    }
    this.serialNumbers.add(serialNumbersItem);
    return this;
  }

   /**
   * Get serialNumbers
   * @return serialNumbers
  **/
  @ApiModelProperty(value = "")
  public List<List<String>> getSerialNumbers() {
    return serialNumbers;
  }

  public void setSerialNumbers(List<List<String>> serialNumbers) {
    this.serialNumbers = serialNumbers;
  }

  public ConfirmItemRow invoiceDate(LocalDate invoiceDate) {
    this.invoiceDate = invoiceDate;
    return this;
  }

   /**
   * Get invoiceDate
   * @return invoiceDate
  **/
  @ApiModelProperty(required = true, value = "")
  public LocalDate getInvoiceDate() {
    return invoiceDate;
  }

  public void setInvoiceDate(LocalDate invoiceDate) {
    this.invoiceDate = invoiceDate;
  }

  public ConfirmItemRow invoiceNumber(String invoiceNumber) {
    this.invoiceNumber = invoiceNumber;
    return this;
  }

   /**
   * Get invoiceNumber
   * @return invoiceNumber
  **/
  @ApiModelProperty(value = "")
  public String getInvoiceNumber() {
    return invoiceNumber;
  }

  public void setInvoiceNumber(String invoiceNumber) {
    this.invoiceNumber = invoiceNumber;
  }

  public ConfirmItemRow orderItemId(String orderItemId) {
    this.orderItemId = orderItemId;
    return this;
  }

   /**
   * Get orderItemId
   * @return orderItemId
  **/
  @ApiModelProperty(value = "")
  public String getOrderItemId() {
    return orderItemId;
  }

  public void setOrderItemId(String orderItemId) {
    this.orderItemId = orderItemId;
  }

  public ConfirmItemRow taxRate(BigDecimal taxRate) {
    this.taxRate = taxRate;
    return this;
  }

   /**
   * Get taxRate
   * @return taxRate
  **/
  @ApiModelProperty(required = true, value = "")
  public BigDecimal getTaxRate() {
    return taxRate;
  }

  public void setTaxRate(BigDecimal taxRate) {
    this.taxRate = taxRate;
  }

  public ConfirmItemRow quantity(Integer quantity) {
    this.quantity = quantity;
    return this;
  }

   /**
   * Get quantity
   * minimum: 1
   * @return quantity
  **/
  @ApiModelProperty(value = "")
  public Integer getQuantity() {
    return quantity;
  }

  public void setQuantity(Integer quantity) {
    this.quantity = quantity;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConfirmItemRow confirmItemRow = (ConfirmItemRow) o;
    return Objects.equals(this.serialNumbers, confirmItemRow.serialNumbers) &&
        Objects.equals(this.invoiceDate, confirmItemRow.invoiceDate) &&
        Objects.equals(this.invoiceNumber, confirmItemRow.invoiceNumber) &&
        Objects.equals(this.orderItemId, confirmItemRow.orderItemId) &&
        Objects.equals(this.taxRate, confirmItemRow.taxRate) &&
        Objects.equals(this.quantity, confirmItemRow.quantity);
  }

  @Override
  public int hashCode() {
    return Objects.hash(serialNumbers, invoiceDate, invoiceNumber, orderItemId, taxRate, quantity);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConfirmItemRow {\n");
    
    sb.append("    serialNumbers: ").append(toIndentedString(serialNumbers)).append("\n");
    sb.append("    invoiceDate: ").append(toIndentedString(invoiceDate)).append("\n");
    sb.append("    invoiceNumber: ").append(toIndentedString(invoiceNumber)).append("\n");
    sb.append("    orderItemId: ").append(toIndentedString(orderItemId)).append("\n");
    sb.append("    taxRate: ").append(toIndentedString(taxRate)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

