/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.flipkart.api.seller.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.flipkart.api.seller.client.model.CourierDetails;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Courier
 */

public class Courier {
  @JsonProperty("pickupDetails")
  private CourierDetails pickupDetails = null;

  @JsonProperty("deliveryDetails")
  private CourierDetails deliveryDetails = null;

  public Courier pickupDetails(CourierDetails pickupDetails) {
    this.pickupDetails = pickupDetails;
    return this;
  }

   /**
   * Get pickupDetails
   * @return pickupDetails
  **/
  @ApiModelProperty(value = "")
  public CourierDetails getPickupDetails() {
    return pickupDetails;
  }

  public void setPickupDetails(CourierDetails pickupDetails) {
    this.pickupDetails = pickupDetails;
  }

  public Courier deliveryDetails(CourierDetails deliveryDetails) {
    this.deliveryDetails = deliveryDetails;
    return this;
  }

   /**
   * Get deliveryDetails
   * @return deliveryDetails
  **/
  @ApiModelProperty(value = "")
  public CourierDetails getDeliveryDetails() {
    return deliveryDetails;
  }

  public void setDeliveryDetails(CourierDetails deliveryDetails) {
    this.deliveryDetails = deliveryDetails;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Courier courier = (Courier) o;
    return Objects.equals(this.pickupDetails, courier.pickupDetails) &&
        Objects.equals(this.deliveryDetails, courier.deliveryDetails);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pickupDetails, deliveryDetails);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Courier {\n");
    
    sb.append("    pickupDetails: ").append(toIndentedString(pickupDetails)).append("\n");
    sb.append("    deliveryDetails: ").append(toIndentedString(deliveryDetails)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

