/*
 * Flipkart Marketplace API
 * This API is offered by Flipkart Marketplace to sellers and partners for orders and listing management. <br /><br />You will need an access token to explore our APIs in the sandbox environment. For details on getting an access token, refer to the <a href='https://seller.flipkart.com/api-docs/FMSAPI.html#sandbox-environment'> documentation</a>. <br />Once you get the access token, use it to authorize the requests using the  <code>Authorize</code> button below. e.g. if your access token is <code>ACCTOK1</code>, the input for authorization should be <code>Bearer ACCTOK1</code>
 *
 * OpenAPI spec version: 3.0
 * Contact: seller-api-queries@flipkart.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.flipkart.api.seller.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.flipkart.api.seller.client.model.CreateOrderItemResponse;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * CreateTestOrdersResponse
 */
public class CreateTestOrdersResponse {
  @JsonProperty("orderId")
  private String orderId = null;

  @JsonProperty("orderItems")
  private List<CreateOrderItemResponse> orderItems = null;

  public CreateTestOrdersResponse orderId(String orderId) {
    this.orderId = orderId;
    return this;
  }

  /**
   * Get orderId
   * @return orderId
   **/
  @ApiModelProperty(value = "")
  public String getOrderId() {
    return orderId;
  }

  public void setOrderId(String orderId) {
    this.orderId = orderId;
  }

  public CreateTestOrdersResponse orderItems(List<CreateOrderItemResponse> orderItems) {
    this.orderItems = orderItems;
    return this;
  }

  public CreateTestOrdersResponse addOrderItemsItem(CreateOrderItemResponse orderItemsItem) {
    if (this.orderItems == null) {
      this.orderItems = new ArrayList<CreateOrderItemResponse>();
    }
    this.orderItems.add(orderItemsItem);
    return this;
  }

  /**
   * Get orderItems
   * @return orderItems
   **/
  @ApiModelProperty(value = "")
  public List<CreateOrderItemResponse> getOrderItems() {
    return orderItems;
  }

  public void setOrderItems(List<CreateOrderItemResponse> orderItems) {
    this.orderItems = orderItems;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateTestOrdersResponse createTestOrdersResponse = (CreateTestOrdersResponse) o;
    return Objects.equals(this.orderId, createTestOrdersResponse.orderId) &&
        Objects.equals(this.orderItems, createTestOrdersResponse.orderItems);
  }

  @Override
  public int hashCode() {
    return Objects.hash(orderId, orderItems);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateTestOrdersResponse {\n");

    sb.append("    orderId: ").append(toIndentedString(orderId)).append("\n");
    sb.append("    orderItems: ").append(toIndentedString(orderItems)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

