package com.flipkart.api.seller.client.model;

/*
 * listings-flipkart-v3
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.flipkart.api.seller.client.model.AddressLabel;
import com.flipkart.api.seller.client.model.DatingLabel;
import com.flipkart.api.seller.client.model.Fulfillment;
import com.flipkart.api.seller.client.model.Location;
import com.flipkart.api.seller.client.model.ModelPackage;
import com.flipkart.api.seller.client.model.Price;
import com.flipkart.api.seller.client.model.ShippingFees;
import com.flipkart.api.seller.client.model.Tax;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.flipkart.api.seller.client.JSON;


/**
 * CreateListingRequest
 */
@JsonPropertyOrder({
    CreateListingRequest.JSON_PROPERTY_PRODUCT_ID,
    CreateListingRequest.JSON_PROPERTY_PRICE,
    CreateListingRequest.JSON_PROPERTY_TAX,
    CreateListingRequest.JSON_PROPERTY_LISTING_STATUS,
    CreateListingRequest.JSON_PROPERTY_SHIPPING_FEES,
    CreateListingRequest.JSON_PROPERTY_SUBSIDIZED_SHIPPING,
    CreateListingRequest.JSON_PROPERTY_FULFILLMENT_PROFILE,
    CreateListingRequest.JSON_PROPERTY_FULFILLMENT,
    CreateListingRequest.JSON_PROPERTY_PACKAGES,
    CreateListingRequest.JSON_PROPERTY_LOCATIONS,
    CreateListingRequest.JSON_PROPERTY_ADDRESS_LABEL,
    CreateListingRequest.JSON_PROPERTY_DATING_LABEL
})

public class CreateListingRequest {
  public static final String JSON_PROPERTY_PRODUCT_ID = "product_id";
  private String productId;

  public static final String JSON_PROPERTY_PRICE = "price";
  private Price price;

  public static final String JSON_PROPERTY_TAX = "tax";
  private Tax tax;

  /**
   * Gets or Sets listingStatus
   */
  public enum ListingStatusEnum {
    ACTIVE("ACTIVE"),

    INACTIVE("INACTIVE");

    private String value;

    ListingStatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ListingStatusEnum fromValue(String value) {
      for (ListingStatusEnum b : ListingStatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_LISTING_STATUS = "listing_status";
  private ListingStatusEnum listingStatus;

  public static final String JSON_PROPERTY_SHIPPING_FEES = "shipping_fees";
  private ShippingFees shippingFees;

  public static final String JSON_PROPERTY_SUBSIDIZED_SHIPPING = "subsidized_shipping";
  private Boolean subsidizedShipping;

  /**
   * Gets or Sets fulfillmentProfile
   */
  public enum FulfillmentProfileEnum {
    NON_FBF("NON_FBF"),

    FBF_LITE("FBF_LITE"),

    FBF("FBF");

    private String value;

    FulfillmentProfileEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static FulfillmentProfileEnum fromValue(String value) {
      for (FulfillmentProfileEnum b : FulfillmentProfileEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_FULFILLMENT_PROFILE = "fulfillment_profile";
  private FulfillmentProfileEnum fulfillmentProfile;

  public static final String JSON_PROPERTY_FULFILLMENT = "fulfillment";
  private Fulfillment fulfillment;

  public static final String JSON_PROPERTY_PACKAGES = "packages";
  private Set<ModelPackage> packages = new LinkedHashSet<>();

  public static final String JSON_PROPERTY_LOCATIONS = "locations";
  private Set<Location> locations = new LinkedHashSet<>();

  public static final String JSON_PROPERTY_ADDRESS_LABEL = "address_label";
  private AddressLabel addressLabel;

  public static final String JSON_PROPERTY_DATING_LABEL = "dating_label";
  private DatingLabel datingLabel;

  public CreateListingRequest() {
  }

  public CreateListingRequest productId(String productId) {
    this.productId = productId;
    return this;
  }

  /**
   * Get productId
   * @return productId
   **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_PRODUCT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getProductId() {
    return productId;
  }


  @JsonProperty(JSON_PROPERTY_PRODUCT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProductId(String productId) {
    this.productId = productId;
  }


  public CreateListingRequest price(Price price) {
    this.price = price;
    return this;
  }

  /**
   * Get price
   * @return price
   **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_PRICE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Price getPrice() {
    return price;
  }


  @JsonProperty(JSON_PROPERTY_PRICE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPrice(Price price) {
    this.price = price;
  }


  public CreateListingRequest tax(Tax tax) {
    this.tax = tax;
    return this;
  }

  /**
   * Get tax
   * @return tax
   **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_TAX)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Tax getTax() {
    return tax;
  }


  @JsonProperty(JSON_PROPERTY_TAX)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTax(Tax tax) {
    this.tax = tax;
  }


  public CreateListingRequest listingStatus(ListingStatusEnum listingStatus) {
    this.listingStatus = listingStatus;
    return this;
  }

  /**
   * Get listingStatus
   * @return listingStatus
   **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_LISTING_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ListingStatusEnum getListingStatus() {
    return listingStatus;
  }


  @JsonProperty(JSON_PROPERTY_LISTING_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setListingStatus(ListingStatusEnum listingStatus) {
    this.listingStatus = listingStatus;
  }


  public CreateListingRequest shippingFees(ShippingFees shippingFees) {
    this.shippingFees = shippingFees;
    return this;
  }

  /**
   * Get shippingFees
   * @return shippingFees
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SHIPPING_FEES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ShippingFees getShippingFees() {
    return shippingFees;
  }


  @JsonProperty(JSON_PROPERTY_SHIPPING_FEES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setShippingFees(ShippingFees shippingFees) {
    this.shippingFees = shippingFees;
  }


  public CreateListingRequest subsidizedShipping(Boolean subsidizedShipping) {
    this.subsidizedShipping = subsidizedShipping;
    return this;
  }

  /**
   * Get subsidizedShipping
   * @return subsidizedShipping
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SUBSIDIZED_SHIPPING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getSubsidizedShipping() {
    return subsidizedShipping;
  }


  @JsonProperty(JSON_PROPERTY_SUBSIDIZED_SHIPPING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSubsidizedShipping(Boolean subsidizedShipping) {
    this.subsidizedShipping = subsidizedShipping;
  }


  public CreateListingRequest fulfillmentProfile(FulfillmentProfileEnum fulfillmentProfile) {
    this.fulfillmentProfile = fulfillmentProfile;
    return this;
  }

  /**
   * Get fulfillmentProfile
   * @return fulfillmentProfile
   **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_FULFILLMENT_PROFILE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public FulfillmentProfileEnum getFulfillmentProfile() {
    return fulfillmentProfile;
  }


  @JsonProperty(JSON_PROPERTY_FULFILLMENT_PROFILE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFulfillmentProfile(FulfillmentProfileEnum fulfillmentProfile) {
    this.fulfillmentProfile = fulfillmentProfile;
  }


  public CreateListingRequest fulfillment(Fulfillment fulfillment) {
    this.fulfillment = fulfillment;
    return this;
  }

  /**
   * Get fulfillment
   * @return fulfillment
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_FULFILLMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Fulfillment getFulfillment() {
    return fulfillment;
  }


  @JsonProperty(JSON_PROPERTY_FULFILLMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFulfillment(Fulfillment fulfillment) {
    this.fulfillment = fulfillment;
  }


  public CreateListingRequest packages(Set<ModelPackage> packages) {
    this.packages = packages;
    return this;
  }

  public CreateListingRequest addPackagesItem(ModelPackage packagesItem) {
    this.packages.add(packagesItem);
    return this;
  }

  /**
   * Get packages
   * @return packages
   **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_PACKAGES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Set<ModelPackage> getPackages() {
    return packages;
  }


  @JsonDeserialize(as = LinkedHashSet.class)
  @JsonProperty(JSON_PROPERTY_PACKAGES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPackages(Set<ModelPackage> packages) {
    this.packages = packages;
  }


  public CreateListingRequest locations(Set<Location> locations) {
    this.locations = locations;
    return this;
  }

  public CreateListingRequest addLocationsItem(Location locationsItem) {
    this.locations.add(locationsItem);
    return this;
  }

  /**
   * Get locations
   * @return locations
   **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_LOCATIONS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Set<Location> getLocations() {
    return locations;
  }


  @JsonDeserialize(as = LinkedHashSet.class)
  @JsonProperty(JSON_PROPERTY_LOCATIONS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLocations(Set<Location> locations) {
    this.locations = locations;
  }


  public CreateListingRequest addressLabel(AddressLabel addressLabel) {
    this.addressLabel = addressLabel;
    return this;
  }

  /**
   * Get addressLabel
   * @return addressLabel
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ADDRESS_LABEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AddressLabel getAddressLabel() {
    return addressLabel;
  }


  @JsonProperty(JSON_PROPERTY_ADDRESS_LABEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAddressLabel(AddressLabel addressLabel) {
    this.addressLabel = addressLabel;
  }


  public CreateListingRequest datingLabel(DatingLabel datingLabel) {
    this.datingLabel = datingLabel;
    return this;
  }

  /**
   * Get datingLabel
   * @return datingLabel
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DATING_LABEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DatingLabel getDatingLabel() {
    return datingLabel;
  }


  @JsonProperty(JSON_PROPERTY_DATING_LABEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDatingLabel(DatingLabel datingLabel) {
    this.datingLabel = datingLabel;
  }


  /**
   * Return true if this CreateListingRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateListingRequest createListingRequest = (CreateListingRequest) o;
    return Objects.equals(this.productId, createListingRequest.productId) &&
        Objects.equals(this.price, createListingRequest.price) &&
        Objects.equals(this.tax, createListingRequest.tax) &&
        Objects.equals(this.listingStatus, createListingRequest.listingStatus) &&
        Objects.equals(this.shippingFees, createListingRequest.shippingFees) &&
        Objects.equals(this.subsidizedShipping, createListingRequest.subsidizedShipping) &&
        Objects.equals(this.fulfillmentProfile, createListingRequest.fulfillmentProfile) &&
        Objects.equals(this.fulfillment, createListingRequest.fulfillment) &&
        Objects.equals(this.packages, createListingRequest.packages) &&
        Objects.equals(this.locations, createListingRequest.locations) &&
        Objects.equals(this.addressLabel, createListingRequest.addressLabel) &&
        Objects.equals(this.datingLabel, createListingRequest.datingLabel);
  }

  @Override
  public int hashCode() {
    return Objects.hash(productId, price, tax, listingStatus, shippingFees, subsidizedShipping, fulfillmentProfile, fulfillment, packages, locations, addressLabel, datingLabel);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateListingRequest {\n");
    sb.append("    productId: ").append(toIndentedString(productId)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    tax: ").append(toIndentedString(tax)).append("\n");
    sb.append("    listingStatus: ").append(toIndentedString(listingStatus)).append("\n");
    sb.append("    shippingFees: ").append(toIndentedString(shippingFees)).append("\n");
    sb.append("    subsidizedShipping: ").append(toIndentedString(subsidizedShipping)).append("\n");
    sb.append("    fulfillmentProfile: ").append(toIndentedString(fulfillmentProfile)).append("\n");
    sb.append("    fulfillment: ").append(toIndentedString(fulfillment)).append("\n");
    sb.append("    packages: ").append(toIndentedString(packages)).append("\n");
    sb.append("    locations: ").append(toIndentedString(locations)).append("\n");
    sb.append("    addressLabel: ").append(toIndentedString(addressLabel)).append("\n");
    sb.append("    datingLabel: ").append(toIndentedString(datingLabel)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}


