/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.flipkart.api.seller.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.flipkart.api.seller.client.model.ConfirmItemRow;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.OffsetDateTime;

/**
 * DispatchRequest
 */

public class DispatchRequest {
  @JsonProperty("shipmentId")
  private String shipmentId = null;

  @JsonProperty("tentativeDeliveryDate")
  private OffsetDateTime tentativeDeliveryDate = null;

  @JsonProperty("deliveryPartner")
  private String deliveryPartner = null;

  @JsonProperty("dispatchDate")
  private OffsetDateTime dispatchDate = null;

  @JsonProperty("trackingId")
  private String trackingId = null;

  @JsonProperty("facilityId")
  private String facilityId = null;

  @JsonProperty("locationId")
  private String locationId = null;

  @JsonProperty("orderItems")
  private List<ConfirmItemRow> orderItems = new ArrayList<ConfirmItemRow>();

  public DispatchRequest shipmentId(String shipmentId) {
    this.shipmentId = shipmentId;
    return this;
  }

   /**
   * Get shipmentId
   * @return shipmentId
  **/
  @ApiModelProperty(value = "")
  public String getShipmentId() {
    return shipmentId;
  }

  public void setShipmentId(String shipmentId) {
    this.shipmentId = shipmentId;
  }

  public DispatchRequest tentativeDeliveryDate(OffsetDateTime tentativeDeliveryDate) {
    this.tentativeDeliveryDate = tentativeDeliveryDate;
    return this;
  }

   /**
   * Get tentativeDeliveryDate
   * @return tentativeDeliveryDate
  **/
  @ApiModelProperty(required = true, value = "")
  public OffsetDateTime getTentativeDeliveryDate() {
    return tentativeDeliveryDate;
  }

  public void setTentativeDeliveryDate(OffsetDateTime tentativeDeliveryDate) {
    this.tentativeDeliveryDate = tentativeDeliveryDate;
  }

  public DispatchRequest deliveryPartner(String deliveryPartner) {
    this.deliveryPartner = deliveryPartner;
    return this;
  }

   /**
   * Get deliveryPartner
   * @return deliveryPartner
  **/
  @ApiModelProperty(value = "")
  public String getDeliveryPartner() {
    return deliveryPartner;
  }

  public void setDeliveryPartner(String deliveryPartner) {
    this.deliveryPartner = deliveryPartner;
  }

  public DispatchRequest dispatchDate(OffsetDateTime dispatchDate) {
    this.dispatchDate = dispatchDate;
    return this;
  }

   /**
   * Get dispatchDate
   * @return dispatchDate
  **/
  @ApiModelProperty(required = true, value = "")
  public OffsetDateTime getDispatchDate() {
    return dispatchDate;
  }

  public void setDispatchDate(OffsetDateTime dispatchDate) {
    this.dispatchDate = dispatchDate;
  }

  public DispatchRequest trackingId(String trackingId) {
    this.trackingId = trackingId;
    return this;
  }

   /**
   * Get trackingId
   * @return trackingId
  **/
  @ApiModelProperty(value = "")
  public String getTrackingId() {
    return trackingId;
  }

  public void setTrackingId(String trackingId) {
    this.trackingId = trackingId;
  }

  public DispatchRequest facilityId(String facilityId) {
    this.facilityId = facilityId;
    return this;
  }

   /**
   * Get facilityId
   * @return facilityId
  **/
  @ApiModelProperty(value = "")
  public String getFacilityId() {
    return facilityId;
  }

  public void setFacilityId(String facilityId) {
    this.facilityId = facilityId;
  }

  public DispatchRequest locationId(String locationId) {
    this.locationId = locationId;
    return this;
  }

   /**
   * Get locationId
   * @return locationId
  **/
  @ApiModelProperty(value = "")
  public String getLocationId() {
    return locationId;
  }

  public void setLocationId(String locationId) {
    this.locationId = locationId;
  }

  public DispatchRequest orderItems(List<ConfirmItemRow> orderItems) {
    this.orderItems = orderItems;
    return this;
  }

  public DispatchRequest addOrderItemsItem(ConfirmItemRow orderItemsItem) {
    this.orderItems.add(orderItemsItem);
    return this;
  }

   /**
   * Get orderItems
   * @return orderItems
  **/
  @ApiModelProperty(required = true, value = "")
  public List<ConfirmItemRow> getOrderItems() {
    return orderItems;
  }

  public void setOrderItems(List<ConfirmItemRow> orderItems) {
    this.orderItems = orderItems;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DispatchRequest dispatchRequest = (DispatchRequest) o;
    return Objects.equals(this.shipmentId, dispatchRequest.shipmentId) &&
        Objects.equals(this.tentativeDeliveryDate, dispatchRequest.tentativeDeliveryDate) &&
        Objects.equals(this.deliveryPartner, dispatchRequest.deliveryPartner) &&
        Objects.equals(this.dispatchDate, dispatchRequest.dispatchDate) &&
        Objects.equals(this.trackingId, dispatchRequest.trackingId) &&
        Objects.equals(this.facilityId, dispatchRequest.facilityId) &&
        Objects.equals(this.locationId, dispatchRequest.locationId) &&
        Objects.equals(this.orderItems, dispatchRequest.orderItems);
  }

  @Override
  public int hashCode() {
    return Objects.hash(shipmentId, tentativeDeliveryDate, deliveryPartner, dispatchDate, trackingId, facilityId, locationId, orderItems);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DispatchRequest {\n");
    
    sb.append("    shipmentId: ").append(toIndentedString(shipmentId)).append("\n");
    sb.append("    tentativeDeliveryDate: ").append(toIndentedString(tentativeDeliveryDate)).append("\n");
    sb.append("    deliveryPartner: ").append(toIndentedString(deliveryPartner)).append("\n");
    sb.append("    dispatchDate: ").append(toIndentedString(dispatchDate)).append("\n");
    sb.append("    trackingId: ").append(toIndentedString(trackingId)).append("\n");
    sb.append("    facilityId: ").append(toIndentedString(facilityId)).append("\n");
    sb.append("    locationId: ").append(toIndentedString(locationId)).append("\n");
    sb.append("    orderItems: ").append(toIndentedString(orderItems)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

