/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.flipkart.api.seller.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * DispatchShipmentRequest
 */

public class DispatchShipmentRequest {
  @JsonProperty("shipmentIds")
  private List<String> shipmentIds = null;

  @JsonProperty("locationId")
  private String locationId = null;

  public DispatchShipmentRequest shipmentIds(List<String> shipmentIds) {
    this.shipmentIds = shipmentIds;
    return this;
  }

  public DispatchShipmentRequest addShipmentIdsItem(String shipmentIdsItem) {
    if (this.shipmentIds == null) {
      this.shipmentIds = new ArrayList<String>();
    }
    this.shipmentIds.add(shipmentIdsItem);
    return this;
  }

   /**
   * Get shipmentIds
   * @return shipmentIds
  **/
  @ApiModelProperty(value = "")
  public List<String> getShipmentIds() {
    return shipmentIds;
  }

  public void setShipmentIds(List<String> shipmentIds) {
    this.shipmentIds = shipmentIds;
  }

  public DispatchShipmentRequest locationId(String locationId) {
    this.locationId = locationId;
    return this;
  }

   /**
   * Get locationId
   * @return locationId
  **/
  @ApiModelProperty(value = "")
  public String getLocationId() {
    return locationId;
  }

  public void setLocationId(String locationId) {
    this.locationId = locationId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DispatchShipmentRequest dispatchShipmentRequest = (DispatchShipmentRequest) o;
    return Objects.equals(this.shipmentIds, dispatchShipmentRequest.shipmentIds) &&
        Objects.equals(this.locationId, dispatchShipmentRequest.locationId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(shipmentIds, locationId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DispatchShipmentRequest {\n");
    
    sb.append("    shipmentIds: ").append(toIndentedString(shipmentIds)).append("\n");
    sb.append("    locationId: ").append(toIndentedString(locationId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

