/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.flipkart.api.seller.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.flipkart.api.seller.client.model.DispatchLocation;
import com.flipkart.api.seller.client.model.InvoiceRequest;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.threeten.bp.OffsetDateTime;

/**
 * DispatchRequestV3
 */

public class DispatchRequestV3 {
  @JsonProperty("shipmentId")
  private String shipmentId = null;

  @JsonProperty("tentativeDeliveryDate")
  private OffsetDateTime tentativeDeliveryDate = null;

  @JsonProperty("dispatchDate")
  private OffsetDateTime dispatchDate = null;

  @JsonProperty("deliveryPartner")
  private String deliveryPartner = null;

  @JsonProperty("trackingId")
  private String trackingId = null;

  @JsonProperty("locationId")
  private String locationId = null;

  @JsonProperty("invoice")
  private InvoiceRequest invoice = null;

  @JsonProperty("dispatchLocation")
  private DispatchLocation dispatchLocation = null;

  public DispatchRequestV3 shipmentId(String shipmentId) {
    this.shipmentId = shipmentId;
    return this;
  }

   /**
   * Get shipmentId
   * @return shipmentId
  **/
  @ApiModelProperty(value = "")
  public String getShipmentId() {
    return shipmentId;
  }

  public void setShipmentId(String shipmentId) {
    this.shipmentId = shipmentId;
  }

  public DispatchRequestV3 tentativeDeliveryDate(OffsetDateTime tentativeDeliveryDate) {
    this.tentativeDeliveryDate = tentativeDeliveryDate;
    return this;
  }

   /**
   * Get tentativeDeliveryDate
   * @return tentativeDeliveryDate
  **/
  @ApiModelProperty(required = true, value = "")
  public OffsetDateTime getTentativeDeliveryDate() {
    return tentativeDeliveryDate;
  }

  public void setTentativeDeliveryDate(OffsetDateTime tentativeDeliveryDate) {
    this.tentativeDeliveryDate = tentativeDeliveryDate;
  }

  public DispatchRequestV3 dispatchDate(OffsetDateTime dispatchDate) {
    this.dispatchDate = dispatchDate;
    return this;
  }

   /**
   * Get dispatchDate
   * @return dispatchDate
  **/
  @ApiModelProperty(required = true, value = "")
  public OffsetDateTime getDispatchDate() {
    return dispatchDate;
  }

  public void setDispatchDate(OffsetDateTime dispatchDate) {
    this.dispatchDate = dispatchDate;
  }

  public DispatchRequestV3 deliveryPartner(String deliveryPartner) {
    this.deliveryPartner = deliveryPartner;
    return this;
  }

   /**
   * Get deliveryPartner
   * @return deliveryPartner
  **/
  @ApiModelProperty(value = "")
  public String getDeliveryPartner() {
    return deliveryPartner;
  }

  public void setDeliveryPartner(String deliveryPartner) {
    this.deliveryPartner = deliveryPartner;
  }

  public DispatchRequestV3 trackingId(String trackingId) {
    this.trackingId = trackingId;
    return this;
  }

   /**
   * Get trackingId
   * @return trackingId
  **/
  @ApiModelProperty(value = "")
  public String getTrackingId() {
    return trackingId;
  }

  public void setTrackingId(String trackingId) {
    this.trackingId = trackingId;
  }

  public DispatchRequestV3 locationId(String locationId) {
    this.locationId = locationId;
    return this;
  }

   /**
   * Get locationId
   * @return locationId
  **/
  @ApiModelProperty(value = "")
  public String getLocationId() {
    return locationId;
  }

  public void setLocationId(String locationId) {
    this.locationId = locationId;
  }

  public DispatchRequestV3 invoice(InvoiceRequest invoice) {
    this.invoice = invoice;
    return this;
  }

   /**
   * Get invoice
   * @return invoice
  **/
  @ApiModelProperty(required = true, value = "")
  public InvoiceRequest getInvoice() {
    return invoice;
  }

  public void setInvoice(InvoiceRequest invoice) {
    this.invoice = invoice;
  }

  public DispatchRequestV3 dispatchLocation(DispatchLocation dispatchLocation) {
    this.dispatchLocation = dispatchLocation;
    return this;
  }

   /**
   * Get dispatchLocation
   * @return dispatchLocation
  **/
  @ApiModelProperty(value = "")
  public DispatchLocation getDispatchLocation() {
    return dispatchLocation;
  }

  public void setDispatchLocation(DispatchLocation dispatchLocation) {
    this.dispatchLocation = dispatchLocation;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DispatchRequestV3 dispatchRequestV3 = (DispatchRequestV3) o;
    return Objects.equals(this.shipmentId, dispatchRequestV3.shipmentId) &&
        Objects.equals(this.tentativeDeliveryDate, dispatchRequestV3.tentativeDeliveryDate) &&
        Objects.equals(this.dispatchDate, dispatchRequestV3.dispatchDate) &&
        Objects.equals(this.deliveryPartner, dispatchRequestV3.deliveryPartner) &&
        Objects.equals(this.trackingId, dispatchRequestV3.trackingId) &&
        Objects.equals(this.locationId, dispatchRequestV3.locationId) &&
        Objects.equals(this.invoice, dispatchRequestV3.invoice) &&
        Objects.equals(this.dispatchLocation, dispatchRequestV3.dispatchLocation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(shipmentId, tentativeDeliveryDate, dispatchDate, deliveryPartner, trackingId, locationId, invoice, dispatchLocation);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DispatchRequestV3 {\n");
    
    sb.append("    shipmentId: ").append(toIndentedString(shipmentId)).append("\n");
    sb.append("    tentativeDeliveryDate: ").append(toIndentedString(tentativeDeliveryDate)).append("\n");
    sb.append("    dispatchDate: ").append(toIndentedString(dispatchDate)).append("\n");
    sb.append("    deliveryPartner: ").append(toIndentedString(deliveryPartner)).append("\n");
    sb.append("    trackingId: ").append(toIndentedString(trackingId)).append("\n");
    sb.append("    locationId: ").append(toIndentedString(locationId)).append("\n");
    sb.append("    invoice: ").append(toIndentedString(invoice)).append("\n");
    sb.append("    dispatchLocation: ").append(toIndentedString(dispatchLocation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

