/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.flipkart.api.seller.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.threeten.bp.OffsetDateTime;

/**
 * FailureAttributes
 */
public class FailureAttributes {
  @JsonProperty("reason")
  private String reason = null;

  @JsonProperty("subReason")
  private String subReason = null;

  @JsonProperty("newDeliveryDate")
  private OffsetDateTime newDeliveryDate = null;

  public FailureAttributes reason(String reason) {
    this.reason = reason;
    return this;
  }

   /**
   * Get reason
   * @return reason
  **/
  @ApiModelProperty(value = "")
  public String getReason() {
    return reason;
  }

  public void setReason(String reason) {
    this.reason = reason;
  }

  public FailureAttributes subReason(String subReason) {
    this.subReason = subReason;
    return this;
  }

   /**
   * Get subReason
   * @return subReason
  **/
  @ApiModelProperty(value = "")
  public String getSubReason() {
    return subReason;
  }

  public void setSubReason(String subReason) {
    this.subReason = subReason;
  }

  public FailureAttributes newDeliveryDate(OffsetDateTime newDeliveryDate) {
    this.newDeliveryDate = newDeliveryDate;
    return this;
  }

   /**
   * Get newDeliveryDate
   * @return newDeliveryDate
  **/
  @ApiModelProperty(required = true, value = "")
  public OffsetDateTime getNewDeliveryDate() {
    return newDeliveryDate;
  }

  public void setNewDeliveryDate(OffsetDateTime newDeliveryDate) {
    this.newDeliveryDate = newDeliveryDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FailureAttributes failureAttributes = (FailureAttributes) o;
    return Objects.equals(this.reason, failureAttributes.reason) &&
        Objects.equals(this.subReason, failureAttributes.subReason) &&
        Objects.equals(this.newDeliveryDate, failureAttributes.newDeliveryDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(reason, subReason, newDeliveryDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FailureAttributes {\n");
    
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("    subReason: ").append(toIndentedString(subReason)).append("\n");
    sb.append("    newDeliveryDate: ").append(toIndentedString(newDeliveryDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

