/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.flipkart.api.seller.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.flipkart.api.seller.client.model.GenerateLabelRequestItemV2;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * GenerateLabelRequestV2
 */

public class GenerateLabelRequestV2 {
  @JsonProperty("orderItems")
  private List<GenerateLabelRequestItemV2> orderItems = new ArrayList<GenerateLabelRequestItemV2>();

  public GenerateLabelRequestV2 orderItems(List<GenerateLabelRequestItemV2> orderItems) {
    this.orderItems = orderItems;
    return this;
  }

  public GenerateLabelRequestV2 addOrderItemsItem(GenerateLabelRequestItemV2 orderItemsItem) {
    this.orderItems.add(orderItemsItem);
    return this;
  }

   /**
   * Get orderItems
   * @return orderItems
  **/
  @ApiModelProperty(required = true, value = "")
  public List<GenerateLabelRequestItemV2> getOrderItems() {
    return orderItems;
  }

  public void setOrderItems(List<GenerateLabelRequestItemV2> orderItems) {
    this.orderItems = orderItems;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GenerateLabelRequestV2 generateLabelRequestV2 = (GenerateLabelRequestV2) o;
    return Objects.equals(this.orderItems, generateLabelRequestV2.orderItems);
  }

  @Override
  public int hashCode() {
    return Objects.hash(orderItems);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GenerateLabelRequestV2 {\n");
    
    sb.append("    orderItems: ").append(toIndentedString(orderItems)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

