package com.flipkart.api.seller.client.model;

/*
 * listings-common-v3
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.flipkart.api.seller.client.model.MarketplaceListingDetail;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.HashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.flipkart.api.seller.client.JSON;


/**
 * GetMarketplaceListingDetailsResponse
 */
@JsonPropertyOrder({
    GetMarketplaceListingDetailsResponse.JSON_PROPERTY_AVAILABLE,
    GetMarketplaceListingDetailsResponse.JSON_PROPERTY_UNAVAILABLE,
    GetMarketplaceListingDetailsResponse.JSON_PROPERTY_INVALID
})

public class GetMarketplaceListingDetailsResponse {
  public static final String JSON_PROPERTY_AVAILABLE = "available";
  private Map<String, MarketplaceListingDetail> available = new HashMap<>();

  public static final String JSON_PROPERTY_UNAVAILABLE = "unavailable";
  private Set<String> unavailable = null;

  public static final String JSON_PROPERTY_INVALID = "invalid";
  private Set<String> invalid = null;

  public GetMarketplaceListingDetailsResponse() {
  }

  public GetMarketplaceListingDetailsResponse available(Map<String, MarketplaceListingDetail> available) {
    this.available = available;
    return this;
  }

  public GetMarketplaceListingDetailsResponse putAvailableItem(String key, MarketplaceListingDetail availableItem) {
    this.available.put(key, availableItem);
    return this;
  }

  /**
   * Get available
   * @return available
   **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_AVAILABLE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Map<String, MarketplaceListingDetail> getAvailable() {
    return available;
  }


  @JsonProperty(JSON_PROPERTY_AVAILABLE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAvailable(Map<String, MarketplaceListingDetail> available) {
    this.available = available;
  }


  public GetMarketplaceListingDetailsResponse unavailable(Set<String> unavailable) {
    this.unavailable = unavailable;
    return this;
  }

  public GetMarketplaceListingDetailsResponse addUnavailableItem(String unavailableItem) {
    if (this.unavailable == null) {
      this.unavailable = new LinkedHashSet<>();
    }
    this.unavailable.add(unavailableItem);
    return this;
  }

  /**
   * Get unavailable
   * @return unavailable
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_UNAVAILABLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Set<String> getUnavailable() {
    return unavailable;
  }


  @JsonDeserialize(as = LinkedHashSet.class)
  @JsonProperty(JSON_PROPERTY_UNAVAILABLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUnavailable(Set<String> unavailable) {
    this.unavailable = unavailable;
  }


  public GetMarketplaceListingDetailsResponse invalid(Set<String> invalid) {
    this.invalid = invalid;
    return this;
  }

  public GetMarketplaceListingDetailsResponse addInvalidItem(String invalidItem) {
    if (this.invalid == null) {
      this.invalid = new LinkedHashSet<>();
    }
    this.invalid.add(invalidItem);
    return this;
  }

  /**
   * Get invalid
   * @return invalid
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_INVALID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Set<String> getInvalid() {
    return invalid;
  }


  @JsonDeserialize(as = LinkedHashSet.class)
  @JsonProperty(JSON_PROPERTY_INVALID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInvalid(Set<String> invalid) {
    this.invalid = invalid;
  }


  /**
   * Return true if this GetMarketplaceListingDetailsResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetMarketplaceListingDetailsResponse getMarketplaceListingDetailsResponse = (GetMarketplaceListingDetailsResponse) o;
    return Objects.equals(this.available, getMarketplaceListingDetailsResponse.available) &&
        Objects.equals(this.unavailable, getMarketplaceListingDetailsResponse.unavailable) &&
        Objects.equals(this.invalid, getMarketplaceListingDetailsResponse.invalid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(available, unavailable, invalid);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetMarketplaceListingDetailsResponse {\n");
    sb.append("    available: ").append(toIndentedString(available)).append("\n");
    sb.append("    unavailable: ").append(toIndentedString(unavailable)).append("\n");
    sb.append("    invalid: ").append(toIndentedString(invalid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

