package com.flipkart.api.seller.client.model;

/*
 * listings-common-v3
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.flipkart.api.seller.client.model.Location;
import com.flipkart.api.seller.client.model.ModelPackage;
import com.flipkart.api.seller.client.model.Price;
import com.flipkart.api.seller.client.model.ShippingFees;
import com.flipkart.api.seller.client.model.Tax;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.flipkart.api.seller.client.JSON;


/**
 * MarketplaceListingDetail
 */
@JsonPropertyOrder({
    MarketplaceListingDetail.JSON_PROPERTY_LISTING_ID,
    MarketplaceListingDetail.JSON_PROPERTY_PRODUCT_ID,
    MarketplaceListingDetail.JSON_PROPERTY_PRICE,
    MarketplaceListingDetail.JSON_PROPERTY_TAX,
    MarketplaceListingDetail.JSON_PROPERTY_LISTING_STATUS,
    MarketplaceListingDetail.JSON_PROPERTY_SHIPPING_FEES,
    MarketplaceListingDetail.JSON_PROPERTY_FULFILLMENT_PROFILE,
    MarketplaceListingDetail.JSON_PROPERTY_PACKAGES,
    MarketplaceListingDetail.JSON_PROPERTY_LOCATIONS,
    MarketplaceListingDetail.JSON_PROPERTY_ARCHIVED_STATUS
})

public class MarketplaceListingDetail {
  public static final String JSON_PROPERTY_LISTING_ID = "listing_id";
  private String listingId;

  public static final String JSON_PROPERTY_PRODUCT_ID = "product_id";
  private String productId;

  public static final String JSON_PROPERTY_PRICE = "price";
  private Price price;

  public static final String JSON_PROPERTY_TAX = "tax";
  private Tax tax;

  /**
   * Gets or Sets listingStatus
   */
  public enum ListingStatusEnum {
    ACTIVE("ACTIVE"),

    INACTIVE("INACTIVE");

    private String value;

    ListingStatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ListingStatusEnum fromValue(String value) {
      for (ListingStatusEnum b : ListingStatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_LISTING_STATUS = "listing_status";
  private ListingStatusEnum listingStatus;

  public static final String JSON_PROPERTY_SHIPPING_FEES = "shipping_fees";
  private ShippingFees shippingFees;

  /**
   * Gets or Sets fulfillmentProfile
   */
  public enum FulfillmentProfileEnum {
    NON_FBF("NON_FBF"),

    FBF_LITE("FBF_LITE"),

    FBF("FBF");

    private String value;

    FulfillmentProfileEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static FulfillmentProfileEnum fromValue(String value) {
      for (FulfillmentProfileEnum b : FulfillmentProfileEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_FULFILLMENT_PROFILE = "fulfillment_profile";
  private FulfillmentProfileEnum fulfillmentProfile;

  public static final String JSON_PROPERTY_PACKAGES = "packages";
  private Set<ModelPackage> packages = null;

  public static final String JSON_PROPERTY_LOCATIONS = "locations";
  private List<Location> locations = null;

  /**
   * Gets or Sets archivedStatus
   */
  public enum ArchivedStatusEnum {
    ARCHIVED("ARCHIVED"),

    NONE("NONE");

    private String value;

    ArchivedStatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ArchivedStatusEnum fromValue(String value) {
      for (ArchivedStatusEnum b : ArchivedStatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_ARCHIVED_STATUS = "archived_status";
  private ArchivedStatusEnum archivedStatus;

  public MarketplaceListingDetail() {
  }

  public MarketplaceListingDetail listingId(String listingId) {
    this.listingId = listingId;
    return this;
  }

  /**
   * Get listingId
   * @return listingId
   **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_LISTING_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getListingId() {
    return listingId;
  }


  @JsonProperty(JSON_PROPERTY_LISTING_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setListingId(String listingId) {
    this.listingId = listingId;
  }


  public MarketplaceListingDetail productId(String productId) {
    this.productId = productId;
    return this;
  }

  /**
   * Get productId
   * @return productId
   **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_PRODUCT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getProductId() {
    return productId;
  }


  @JsonProperty(JSON_PROPERTY_PRODUCT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProductId(String productId) {
    this.productId = productId;
  }


  public MarketplaceListingDetail price(Price price) {
    this.price = price;
    return this;
  }

  /**
   * Get price
   * @return price
   **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_PRICE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Price getPrice() {
    return price;
  }


  @JsonProperty(JSON_PROPERTY_PRICE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPrice(Price price) {
    this.price = price;
  }


  public MarketplaceListingDetail tax(Tax tax) {
    this.tax = tax;
    return this;
  }

  /**
   * Get tax
   * @return tax
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TAX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Tax getTax() {
    return tax;
  }


  @JsonProperty(JSON_PROPERTY_TAX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTax(Tax tax) {
    this.tax = tax;
  }


  public MarketplaceListingDetail listingStatus(ListingStatusEnum listingStatus) {
    this.listingStatus = listingStatus;
    return this;
  }

  /**
   * Get listingStatus
   * @return listingStatus
   **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_LISTING_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ListingStatusEnum getListingStatus() {
    return listingStatus;
  }


  @JsonProperty(JSON_PROPERTY_LISTING_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setListingStatus(ListingStatusEnum listingStatus) {
    this.listingStatus = listingStatus;
  }


  public MarketplaceListingDetail shippingFees(ShippingFees shippingFees) {
    this.shippingFees = shippingFees;
    return this;
  }

  /**
   * Get shippingFees
   * @return shippingFees
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SHIPPING_FEES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ShippingFees getShippingFees() {
    return shippingFees;
  }


  @JsonProperty(JSON_PROPERTY_SHIPPING_FEES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setShippingFees(ShippingFees shippingFees) {
    this.shippingFees = shippingFees;
  }


  public MarketplaceListingDetail fulfillmentProfile(FulfillmentProfileEnum fulfillmentProfile) {
    this.fulfillmentProfile = fulfillmentProfile;
    return this;
  }

  /**
   * Get fulfillmentProfile
   * @return fulfillmentProfile
   **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_FULFILLMENT_PROFILE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public FulfillmentProfileEnum getFulfillmentProfile() {
    return fulfillmentProfile;
  }


  @JsonProperty(JSON_PROPERTY_FULFILLMENT_PROFILE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFulfillmentProfile(FulfillmentProfileEnum fulfillmentProfile) {
    this.fulfillmentProfile = fulfillmentProfile;
  }


  public MarketplaceListingDetail packages(Set<ModelPackage> packages) {
    this.packages = packages;
    return this;
  }

  public MarketplaceListingDetail addPackagesItem(ModelPackage packagesItem) {
    if (this.packages == null) {
      this.packages = new LinkedHashSet<>();
    }
    this.packages.add(packagesItem);
    return this;
  }

  /**
   * Get packages
   * @return packages
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PACKAGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Set<ModelPackage> getPackages() {
    return packages;
  }


  @JsonDeserialize(as = LinkedHashSet.class)
  @JsonProperty(JSON_PROPERTY_PACKAGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPackages(Set<ModelPackage> packages) {
    this.packages = packages;
  }


  public MarketplaceListingDetail locations(List<Location> locations) {
    this.locations = locations;
    return this;
  }

  public MarketplaceListingDetail addLocationsItem(Location locationsItem) {
    if (this.locations == null) {
      this.locations = new ArrayList<>();
    }
    this.locations.add(locationsItem);
    return this;
  }

  /**
   * Get locations
   * @return locations
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_LOCATIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Location> getLocations() {
    return locations;
  }


  @JsonProperty(JSON_PROPERTY_LOCATIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLocations(List<Location> locations) {
    this.locations = locations;
  }


  public MarketplaceListingDetail archivedStatus(ArchivedStatusEnum archivedStatus) {
    this.archivedStatus = archivedStatus;
    return this;
  }

  /**
   * Get archivedStatus
   * @return archivedStatus
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ARCHIVED_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ArchivedStatusEnum getArchivedStatus() {
    return archivedStatus;
  }


  @JsonProperty(JSON_PROPERTY_ARCHIVED_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setArchivedStatus(ArchivedStatusEnum archivedStatus) {
    this.archivedStatus = archivedStatus;
  }


  /**
   * Return true if this MarketplaceListingDetail object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MarketplaceListingDetail marketplaceListingDetail = (MarketplaceListingDetail) o;
    return Objects.equals(this.listingId, marketplaceListingDetail.listingId) &&
        Objects.equals(this.productId, marketplaceListingDetail.productId) &&
        Objects.equals(this.price, marketplaceListingDetail.price) &&
        Objects.equals(this.tax, marketplaceListingDetail.tax) &&
        Objects.equals(this.listingStatus, marketplaceListingDetail.listingStatus) &&
        Objects.equals(this.shippingFees, marketplaceListingDetail.shippingFees) &&
        Objects.equals(this.fulfillmentProfile, marketplaceListingDetail.fulfillmentProfile) &&
        Objects.equals(this.packages, marketplaceListingDetail.packages) &&
        Objects.equals(this.locations, marketplaceListingDetail.locations) &&
        Objects.equals(this.archivedStatus, marketplaceListingDetail.archivedStatus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(listingId, productId, price, tax, listingStatus, shippingFees, fulfillmentProfile, packages, locations, archivedStatus);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MarketplaceListingDetail {\n");
    sb.append("    listingId: ").append(toIndentedString(listingId)).append("\n");
    sb.append("    productId: ").append(toIndentedString(productId)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    tax: ").append(toIndentedString(tax)).append("\n");
    sb.append("    listingStatus: ").append(toIndentedString(listingStatus)).append("\n");
    sb.append("    shippingFees: ").append(toIndentedString(shippingFees)).append("\n");
    sb.append("    fulfillmentProfile: ").append(toIndentedString(fulfillmentProfile)).append("\n");
    sb.append("    packages: ").append(toIndentedString(packages)).append("\n");
    sb.append("    locations: ").append(toIndentedString(locations)).append("\n");
    sb.append("    archivedStatus: ").append(toIndentedString(archivedStatus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}


