/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.flipkart.api.seller.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.flipkart.api.seller.client.model.Dimensions;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * ModelPackage
 */

public class ModelPackage {
  @JsonProperty("packageId")
  private String packageId = null;

  @JsonProperty("packageTitle")
  private String packageTitle = null;

  @JsonProperty("packageSku")
  private String packageSku = null;

  @JsonProperty("dimensions")
  private Dimensions dimensions = null;

  public ModelPackage packageId(String packageId) {
    this.packageId = packageId;
    return this;
  }

   /**
   * Get packageId
   * @return packageId
  **/
  @ApiModelProperty(value = "")
  public String getPackageId() {
    return packageId;
  }

  public void setPackageId(String packageId) {
    this.packageId = packageId;
  }

  public ModelPackage packageTitle(String packageTitle) {
    this.packageTitle = packageTitle;
    return this;
  }

   /**
   * Get packageTitle
   * @return packageTitle
  **/
  @ApiModelProperty(value = "")
  public String getPackageTitle() {
    return packageTitle;
  }

  public void setPackageTitle(String packageTitle) {
    this.packageTitle = packageTitle;
  }

  public ModelPackage packageSku(String packageSku) {
    this.packageSku = packageSku;
    return this;
  }

   /**
   * Get packageSku
   * @return packageSku
  **/
  @ApiModelProperty(value = "")
  public String getPackageSku() {
    return packageSku;
  }

  public void setPackageSku(String packageSku) {
    this.packageSku = packageSku;
  }

  public ModelPackage dimensions(Dimensions dimensions) {
    this.dimensions = dimensions;
    return this;
  }

   /**
   * Get dimensions
   * @return dimensions
  **/
  @ApiModelProperty(value = "")
  public Dimensions getDimensions() {
    return dimensions;
  }

  public void setDimensions(Dimensions dimensions) {
    this.dimensions = dimensions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModelPackage _package = (ModelPackage) o;
    return Objects.equals(this.packageId, _package.packageId) &&
        Objects.equals(this.packageTitle, _package.packageTitle) &&
        Objects.equals(this.packageSku, _package.packageSku) &&
        Objects.equals(this.dimensions, _package.dimensions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(packageId, packageTitle, packageSku, dimensions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModelPackage {\n");
    
    sb.append("    packageId: ").append(toIndentedString(packageId)).append("\n");
    sb.append("    packageTitle: ").append(toIndentedString(packageTitle)).append("\n");
    sb.append("    packageSku: ").append(toIndentedString(packageSku)).append("\n");
    sb.append("    dimensions: ").append(toIndentedString(dimensions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

