/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.flipkart.api.seller.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.flipkart.api.seller.client.model.TaxDetails;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

/**
 * OrderItems
 */

public class OrderItems {
  @JsonProperty("orderItemId")
  private String orderItemId = null;

  @JsonProperty("invoiceAmount")
  private BigDecimal invoiceAmount = null;

  @JsonProperty("taxRate")
  private BigDecimal taxRate = null;

  @JsonProperty("serialNumbers")
  private List<List<String>> serialNumbers = null;

  @JsonProperty("taxDetails")
  private TaxDetails taxDetails = null;

  public OrderItems orderItemId(String orderItemId) {
    this.orderItemId = orderItemId;
    return this;
  }

   /**
   * Get orderItemId
   * @return orderItemId
  **/
  @ApiModelProperty(value = "")
  public String getOrderItemId() {
    return orderItemId;
  }

  public void setOrderItemId(String orderItemId) {
    this.orderItemId = orderItemId;
  }

  public OrderItems invoiceAmount(BigDecimal invoiceAmount) {
    this.invoiceAmount = invoiceAmount;
    return this;
  }

   /**
   * Get invoiceAmount
   * @return invoiceAmount
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getInvoiceAmount() {
    return invoiceAmount;
  }

  public void setInvoiceAmount(BigDecimal invoiceAmount) {
    this.invoiceAmount = invoiceAmount;
  }

  public OrderItems taxRate(BigDecimal taxRate) {
    this.taxRate = taxRate;
    return this;
  }

   /**
   * Get taxRate
   * @return taxRate
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getTaxRate() {
    return taxRate;
  }

  public void setTaxRate(BigDecimal taxRate) {
    this.taxRate = taxRate;
  }

  public OrderItems serialNumbers(List<List<String>> serialNumbers) {
    this.serialNumbers = serialNumbers;
    return this;
  }

  public OrderItems addSerialNumbersItem(List<String> serialNumbersItem) {
    if (this.serialNumbers == null) {
      this.serialNumbers = new ArrayList<List<String>>();
    }
    this.serialNumbers.add(serialNumbersItem);
    return this;
  }

   /**
   * Get serialNumbers
   * @return serialNumbers
  **/
  @ApiModelProperty(value = "")
  public List<List<String>> getSerialNumbers() {
    return serialNumbers;
  }

  public void setSerialNumbers(List<List<String>> serialNumbers) {
    this.serialNumbers = serialNumbers;
  }

  public OrderItems taxDetails(TaxDetails taxDetails) {
    this.taxDetails = taxDetails;
    return this;
  }

   /**
   * Get taxDetails
   * @return taxDetails
  **/
  @ApiModelProperty(value = "")
  public TaxDetails getTaxDetails() {
    return taxDetails;
  }

  public void setTaxDetails(TaxDetails taxDetails) {
    this.taxDetails = taxDetails;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderItems orderItems = (OrderItems) o;
    return Objects.equals(this.orderItemId, orderItems.orderItemId) &&
        Objects.equals(this.invoiceAmount, orderItems.invoiceAmount) &&
        Objects.equals(this.taxRate, orderItems.taxRate) &&
        Objects.equals(this.serialNumbers, orderItems.serialNumbers) &&
        Objects.equals(this.taxDetails, orderItems.taxDetails);
  }

  @Override
  public int hashCode() {
    return Objects.hash(orderItemId, invoiceAmount, taxRate, serialNumbers, taxDetails);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderItems {\n");
    
    sb.append("    orderItemId: ").append(toIndentedString(orderItemId)).append("\n");
    sb.append("    invoiceAmount: ").append(toIndentedString(invoiceAmount)).append("\n");
    sb.append("    taxRate: ").append(toIndentedString(taxRate)).append("\n");
    sb.append("    serialNumbers: ").append(toIndentedString(serialNumbers)).append("\n");
    sb.append("    taxDetails: ").append(toIndentedString(taxDetails)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

