/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.flipkart.api.seller.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.flipkart.api.seller.client.model.FailedCancellations;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * OrderItemCancelResponse
 */

public class OrderItemCancelResponse {
  @JsonProperty("cancelled")
  private List<String> cancelled = null;

  @JsonProperty("failedCancellations")
  private List<FailedCancellations> failedCancellations = null;

  public OrderItemCancelResponse cancelled(List<String> cancelled) {
    this.cancelled = cancelled;
    return this;
  }

  public OrderItemCancelResponse addCancelledItem(String cancelledItem) {
    if (this.cancelled == null) {
      this.cancelled = new ArrayList<String>();
    }
    this.cancelled.add(cancelledItem);
    return this;
  }

   /**
   * Get cancelled
   * @return cancelled
  **/
  @ApiModelProperty(value = "")
  public List<String> getCancelled() {
    return cancelled;
  }

  public void setCancelled(List<String> cancelled) {
    this.cancelled = cancelled;
  }

  public OrderItemCancelResponse failedCancellations(List<FailedCancellations> failedCancellations) {
    this.failedCancellations = failedCancellations;
    return this;
  }

  public OrderItemCancelResponse addFailedCancellationsItem(FailedCancellations failedCancellationsItem) {
    if (this.failedCancellations == null) {
      this.failedCancellations = new ArrayList<FailedCancellations>();
    }
    this.failedCancellations.add(failedCancellationsItem);
    return this;
  }

   /**
   * Get failedCancellations
   * @return failedCancellations
  **/
  @ApiModelProperty(value = "")
  public List<FailedCancellations> getFailedCancellations() {
    return failedCancellations;
  }

  public void setFailedCancellations(List<FailedCancellations> failedCancellations) {
    this.failedCancellations = failedCancellations;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderItemCancelResponse orderItemCancelResponse = (OrderItemCancelResponse) o;
    return Objects.equals(this.cancelled, orderItemCancelResponse.cancelled) &&
        Objects.equals(this.failedCancellations, orderItemCancelResponse.failedCancellations);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cancelled, failedCancellations);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderItemCancelResponse {\n");
    
    sb.append("    cancelled: ").append(toIndentedString(cancelled)).append("\n");
    sb.append("    failedCancellations: ").append(toIndentedString(failedCancellations)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

