/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.flipkart.api.seller.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.flipkart.api.seller.client.model.PickUpDate;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Params
 */

public class Params {
  @JsonProperty("vendorGroupCode")
  private String vendorGroupCode = null;

  @JsonProperty("pickupDate")
  private PickUpDate pickupDate = null;

  @JsonProperty("locationId")
  private String locationId = null;

  @JsonProperty("is_mps")
  private Boolean isMps = null;

  public Params vendorGroupCode(String vendorGroupCode) {
    this.vendorGroupCode = vendorGroupCode;
    return this;
  }

   /**
   * Get vendorGroupCode
   * @return vendorGroupCode
  **/
  @ApiModelProperty(required = true, value = "")
  public String getVendorGroupCode() {
    return vendorGroupCode;
  }

  public void setVendorGroupCode(String vendorGroupCode) {
    this.vendorGroupCode = vendorGroupCode;
  }

  public Params pickupDate(PickUpDate pickupDate) {
    this.pickupDate = pickupDate;
    return this;
  }

   /**
   * Get pickupDate
   * @return pickupDate
  **/
  @ApiModelProperty(value = "")
  public PickUpDate getPickupDate() {
    return pickupDate;
  }

  public void setPickupDate(PickUpDate pickupDate) {
    this.pickupDate = pickupDate;
  }

  public Params locationId(String locationId) {
    this.locationId = locationId;
    return this;
  }

   /**
   * Get locationId
   * @return locationId
  **/
  @ApiModelProperty(value = "")
  public String getLocationId() {
    return locationId;
  }

  public void setLocationId(String locationId) {
    this.locationId = locationId;
  }

  public Params isMps(Boolean isMps) {
    this.isMps = isMps;
    return this;
  }

   /**
   * Get isMps
   * @return isMps
  **/
  @ApiModelProperty(value = "")
  public Boolean isIsMps() {
    return isMps;
  }

  public void setIsMps(Boolean isMps) {
    this.isMps = isMps;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Params params = (Params) o;
    return Objects.equals(this.vendorGroupCode, params.vendorGroupCode) &&
        Objects.equals(this.pickupDate, params.pickupDate) &&
        Objects.equals(this.locationId, params.locationId) &&
        Objects.equals(this.isMps, params.isMps);
  }

  @Override
  public int hashCode() {
    return Objects.hash(vendorGroupCode, pickupDate, locationId, isMps);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Params {\n");
    
    sb.append("    vendorGroupCode: ").append(toIndentedString(vendorGroupCode)).append("\n");
    sb.append("    pickupDate: ").append(toIndentedString(pickupDate)).append("\n");
    sb.append("    locationId: ").append(toIndentedString(locationId)).append("\n");
    sb.append("    isMps: ").append(toIndentedString(isMps)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

