/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.flipkart.api.seller.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;

/**
 * PriceComponent
 */

public class PriceComponent {
  @JsonProperty("sellingPrice")
  private BigDecimal sellingPrice = null;

  @JsonProperty("totalPrice")
  private BigDecimal totalPrice = null;

  @JsonProperty("shippingCharge")
  private BigDecimal shippingCharge = null;

  @JsonProperty("customerPrice")
  private BigDecimal customerPrice = null;

  @JsonProperty("flipkartDiscount")
  private BigDecimal flipkartDiscount = null;

  public PriceComponent sellingPrice(BigDecimal sellingPrice) {
    this.sellingPrice = sellingPrice;
    return this;
  }

   /**
   * Get sellingPrice
   * @return sellingPrice
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getSellingPrice() {
    return sellingPrice;
  }

  public void setSellingPrice(BigDecimal sellingPrice) {
    this.sellingPrice = sellingPrice;
  }

  public PriceComponent totalPrice(BigDecimal totalPrice) {
    this.totalPrice = totalPrice;
    return this;
  }

   /**
   * Get totalPrice
   * @return totalPrice
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getTotalPrice() {
    return totalPrice;
  }

  public void setTotalPrice(BigDecimal totalPrice) {
    this.totalPrice = totalPrice;
  }

  public PriceComponent shippingCharge(BigDecimal shippingCharge) {
    this.shippingCharge = shippingCharge;
    return this;
  }

   /**
   * Get shippingCharge
   * @return shippingCharge
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getShippingCharge() {
    return shippingCharge;
  }

  public void setShippingCharge(BigDecimal shippingCharge) {
    this.shippingCharge = shippingCharge;
  }

  public PriceComponent customerPrice(BigDecimal customerPrice) {
    this.customerPrice = customerPrice;
    return this;
  }

   /**
   * Get customerPrice
   * @return customerPrice
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getCustomerPrice() {
    return customerPrice;
  }

  public void setCustomerPrice(BigDecimal customerPrice) {
    this.customerPrice = customerPrice;
  }

  public PriceComponent flipkartDiscount(BigDecimal flipkartDiscount) {
    this.flipkartDiscount = flipkartDiscount;
    return this;
  }

   /**
   * Get flipkartDiscount
   * @return flipkartDiscount
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getFlipkartDiscount() {
    return flipkartDiscount;
  }

  public void setFlipkartDiscount(BigDecimal flipkartDiscount) {
    this.flipkartDiscount = flipkartDiscount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PriceComponent priceComponent = (PriceComponent) o;
    return Objects.equals(this.sellingPrice, priceComponent.sellingPrice) &&
        Objects.equals(this.totalPrice, priceComponent.totalPrice) &&
        Objects.equals(this.shippingCharge, priceComponent.shippingCharge) &&
        Objects.equals(this.customerPrice, priceComponent.customerPrice) &&
        Objects.equals(this.flipkartDiscount, priceComponent.flipkartDiscount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sellingPrice, totalPrice, shippingCharge, customerPrice, flipkartDiscount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PriceComponent {\n");
    
    sb.append("    sellingPrice: ").append(toIndentedString(sellingPrice)).append("\n");
    sb.append("    totalPrice: ").append(toIndentedString(totalPrice)).append("\n");
    sb.append("    shippingCharge: ").append(toIndentedString(shippingCharge)).append("\n");
    sb.append("    customerPrice: ").append(toIndentedString(customerPrice)).append("\n");
    sb.append("    flipkartDiscount: ").append(toIndentedString(flipkartDiscount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

