/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.flipkart.api.seller.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * PriceComponents
 */

public class PriceComponents {
  @JsonProperty("sellingPrice")
  private Float sellingPrice = null;

  @JsonProperty("customerPrice")
  private Float customerPrice = null;

  @JsonProperty("shippingCharge")
  private Float shippingCharge = null;

  @JsonProperty("totalPrice")
  private Float totalPrice = null;

  @JsonProperty("flipkartDiscount")
  private Float flipkartDiscount = null;

  @JsonProperty("subsidy")
  private Float subsidy = null;

  public PriceComponents sellingPrice(Float sellingPrice) {
    this.sellingPrice = sellingPrice;
    return this;
  }

   /**
   * Get sellingPrice
   * @return sellingPrice
  **/
  @ApiModelProperty(value = "")
  public Float getSellingPrice() {
    return sellingPrice;
  }

  public void setSellingPrice(Float sellingPrice) {
    this.sellingPrice = sellingPrice;
  }

  public PriceComponents customerPrice(Float customerPrice) {
    this.customerPrice = customerPrice;
    return this;
  }

   /**
   * Get customerPrice
   * @return customerPrice
  **/
  @ApiModelProperty(value = "")
  public Float getCustomerPrice() {
    return customerPrice;
  }

  public void setCustomerPrice(Float customerPrice) {
    this.customerPrice = customerPrice;
  }

  public PriceComponents shippingCharge(Float shippingCharge) {
    this.shippingCharge = shippingCharge;
    return this;
  }

   /**
   * Get shippingCharge
   * @return shippingCharge
  **/
  @ApiModelProperty(value = "")
  public Float getShippingCharge() {
    return shippingCharge;
  }

  public void setShippingCharge(Float shippingCharge) {
    this.shippingCharge = shippingCharge;
  }

  public PriceComponents totalPrice(Float totalPrice) {
    this.totalPrice = totalPrice;
    return this;
  }

   /**
   * Get totalPrice
   * @return totalPrice
  **/
  @ApiModelProperty(value = "")
  public Float getTotalPrice() {
    return totalPrice;
  }

  public void setTotalPrice(Float totalPrice) {
    this.totalPrice = totalPrice;
  }

  public PriceComponents flipkartDiscount(Float flipkartDiscount) {
    this.flipkartDiscount = flipkartDiscount;
    return this;
  }

   /**
   * Get flipkartDiscount
   * @return flipkartDiscount
  **/
  @ApiModelProperty(value = "")
  public Float getFlipkartDiscount() {
    return flipkartDiscount;
  }

  public void setFlipkartDiscount(Float flipkartDiscount) {
    this.flipkartDiscount = flipkartDiscount;
  }

  public PriceComponents subsidy(Float subsidy) {
    this.subsidy = subsidy;
    return this;
  }

   /**
   * Get subsidy
   * @return subsidy
  **/
  @ApiModelProperty(value = "")
  public Float getSubsidy() {
    return subsidy;
  }

  public void setSubsidy(Float subsidy) {
    this.subsidy = subsidy;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PriceComponents priceComponents = (PriceComponents) o;
    return Objects.equals(this.sellingPrice, priceComponents.sellingPrice) &&
        Objects.equals(this.customerPrice, priceComponents.customerPrice) &&
        Objects.equals(this.shippingCharge, priceComponents.shippingCharge) &&
        Objects.equals(this.totalPrice, priceComponents.totalPrice) &&
        Objects.equals(this.flipkartDiscount, priceComponents.flipkartDiscount) &&
        Objects.equals(this.subsidy, priceComponents.subsidy);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sellingPrice, customerPrice, shippingCharge, totalPrice, flipkartDiscount, subsidy);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PriceComponents {\n");
    
    sb.append("    sellingPrice: ").append(toIndentedString(sellingPrice)).append("\n");
    sb.append("    customerPrice: ").append(toIndentedString(customerPrice)).append("\n");
    sb.append("    shippingCharge: ").append(toIndentedString(shippingCharge)).append("\n");
    sb.append("    totalPrice: ").append(toIndentedString(totalPrice)).append("\n");
    sb.append("    flipkartDiscount: ").append(toIndentedString(flipkartDiscount)).append("\n");
    sb.append("    subsidy: ").append(toIndentedString(subsidy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

