/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.flipkart.api.seller.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.flipkart.api.seller.client.model.ReturnItem;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * ReturnsSearchResponseV2
 */

public class ReturnsSearchResponseV2 {
  @JsonProperty("hasMore")
  private Boolean hasMore = null;

  @JsonProperty("nextUrl")
  private String nextUrl = null;

  @JsonProperty("returnItems")
  private List<ReturnItem> returnItems = null;

  public ReturnsSearchResponseV2 hasMore(Boolean hasMore) {
    this.hasMore = hasMore;
    return this;
  }

   /**
   * Get hasMore
   * @return hasMore
  **/
  @ApiModelProperty(value = "")
  public Boolean isHasMore() {
    return hasMore;
  }

  public void setHasMore(Boolean hasMore) {
    this.hasMore = hasMore;
  }

  public ReturnsSearchResponseV2 nextUrl(String nextUrl) {
    this.nextUrl = nextUrl;
    return this;
  }

   /**
   * Get nextUrl
   * @return nextUrl
  **/
  @ApiModelProperty(value = "")
  public String getNextUrl() {
    return nextUrl;
  }

  public void setNextUrl(String nextUrl) {
    this.nextUrl = nextUrl;
  }

  public ReturnsSearchResponseV2 returnItems(List<ReturnItem> returnItems) {
    this.returnItems = returnItems;
    return this;
  }

  public ReturnsSearchResponseV2 addReturnItemsItem(ReturnItem returnItemsItem) {
    if (this.returnItems == null) {
      this.returnItems = new ArrayList<ReturnItem>();
    }
    this.returnItems.add(returnItemsItem);
    return this;
  }

   /**
   * Get returnItems
   * @return returnItems
  **/
  @ApiModelProperty(value = "")
  public List<ReturnItem> getReturnItems() {
    return returnItems;
  }

  public void setReturnItems(List<ReturnItem> returnItems) {
    this.returnItems = returnItems;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReturnsSearchResponseV2 returnsSearchResponseV2 = (ReturnsSearchResponseV2) o;
    return Objects.equals(this.hasMore, returnsSearchResponseV2.hasMore) &&
        Objects.equals(this.nextUrl, returnsSearchResponseV2.nextUrl) &&
        Objects.equals(this.returnItems, returnsSearchResponseV2.returnItems);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hasMore, nextUrl, returnItems);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReturnsSearchResponseV2 {\n");
    
    sb.append("    hasMore: ").append(toIndentedString(hasMore)).append("\n");
    sb.append("    nextUrl: ").append(toIndentedString(nextUrl)).append("\n");
    sb.append("    returnItems: ").append(toIndentedString(returnItems)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

