/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.flipkart.api.seller.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.flipkart.api.seller.client.model.ReturnRejectRequest;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * ReturnsRejectRequest
 */

public class ReturnsRejectRequest {
  @JsonProperty("returns")
  private List<ReturnRejectRequest> returns = new ArrayList<ReturnRejectRequest>();

  @JsonProperty("locationId")
  private String locationId = null;

  public ReturnsRejectRequest returns(List<ReturnRejectRequest> returns) {
    this.returns = returns;
    return this;
  }

  public ReturnsRejectRequest addReturnsItem(ReturnRejectRequest returnsItem) {
    this.returns.add(returnsItem);
    return this;
  }

   /**
   * Get returns
   * @return returns
  **/
  @ApiModelProperty(required = true, value = "")
  public List<ReturnRejectRequest> getReturns() {
    return returns;
  }

  public void setReturns(List<ReturnRejectRequest> returns) {
    this.returns = returns;
  }

  public ReturnsRejectRequest locationId(String locationId) {
    this.locationId = locationId;
    return this;
  }

   /**
   * Get locationId
   * @return locationId
  **/
  @ApiModelProperty(value = "")
  public String getLocationId() {
    return locationId;
  }

  public void setLocationId(String locationId) {
    this.locationId = locationId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReturnsRejectRequest returnsRejectRequest = (ReturnsRejectRequest) o;
    return Objects.equals(this.returns, returnsRejectRequest.returns) &&
        Objects.equals(this.locationId, returnsRejectRequest.locationId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(returns, locationId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReturnsRejectRequest {\n");
    
    sb.append("    returns: ").append(toIndentedString(returns)).append("\n");
    sb.append("    locationId: ").append(toIndentedString(locationId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

