/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.flipkart.api.seller.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.flipkart.api.seller.client.model.Service;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * ReturnItem
 */

public class ReturnItem {
  @JsonProperty("orderItemId")
  private String orderItemId = null;

  @JsonProperty("locationId")
  private String locationId = null;

  @JsonProperty("orderId")
  private String orderId = null;

  @JsonProperty("quantity")
  private Integer quantity = null;

  @JsonProperty("orderDate")
  private String orderDate = null;

  @JsonProperty("createdDate")
  private String createdDate = null;

  @JsonProperty("courierName")
  private String courierName = null;

  @JsonProperty("sellerId")
  private String sellerId = null;

  @JsonProperty("returnId")
  private String returnId = null;

  @JsonProperty("status")
  private String status = null;

  @JsonProperty("type")
  private String type = null;

  @JsonProperty("reason")
  private String reason = null;

  @JsonProperty("subReason")
  private String subReason = null;

  @JsonProperty("trackingId")
  private String trackingId = null;

  @JsonProperty("shipmentStatus")
  private String shipmentStatus = null;

  @JsonProperty("shipmentId")
  private String shipmentId = null;

  @JsonProperty("comments")
  private String comments = null;

  @JsonProperty("updatedDate")
  private String updatedDate = null;

  @JsonProperty("approvedOn")
  private String approvedOn = null;

  @JsonProperty("expectedDate")
  private String expectedDate = null;

  /**
   * Gets or Sets serviceProfile
   */
  public enum ServiceProfileEnum {
    FLIPKART_FULFILMENT("Flipkart_Fulfilment"),
    
    SELLER_FULFILMENT("Seller_Fulfilment"),
    
    SMART_FULFILMENT("Smart_Fulfilment"),
    
    FBF("FBF"),
    
    NON_FBF("NON_FBF"),
    
    FBF_LITE("FBF_LITE");

    private String value;

    ServiceProfileEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ServiceProfileEnum fromValue(String value) {
      for (ServiceProfileEnum b : ServiceProfileEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("serviceProfile")
  private ServiceProfileEnum serviceProfile = null;

  @JsonProperty("services")
  private List<Service> services = null;

  public ReturnItem orderItemId(String orderItemId) {
    this.orderItemId = orderItemId;
    return this;
  }

   /**
   * Get orderItemId
   * @return orderItemId
  **/
  @ApiModelProperty(value = "")
  public String getOrderItemId() {
    return orderItemId;
  }

  public void setOrderItemId(String orderItemId) {
    this.orderItemId = orderItemId;
  }

  public ReturnItem locationId(String locationId) {
    this.locationId = locationId;
    return this;
  }

   /**
   * Get locationId
   * @return locationId
  **/
  @ApiModelProperty(value = "")
  public String getLocationId() {
    return locationId;
  }

  public void setLocationId(String locationId) {
    this.locationId = locationId;
  }

  public ReturnItem orderId(String orderId) {
    this.orderId = orderId;
    return this;
  }

   /**
   * Get orderId
   * @return orderId
  **/
  @ApiModelProperty(value = "")
  public String getOrderId() {
    return orderId;
  }

  public void setOrderId(String orderId) {
    this.orderId = orderId;
  }

  public ReturnItem quantity(Integer quantity) {
    this.quantity = quantity;
    return this;
  }

   /**
   * Get quantity
   * @return quantity
  **/
  @ApiModelProperty(value = "")
  public Integer getQuantity() {
    return quantity;
  }

  public void setQuantity(Integer quantity) {
    this.quantity = quantity;
  }

  public ReturnItem orderDate(String orderDate) {
    this.orderDate = orderDate;
    return this;
  }

   /**
   * Get orderDate
   * @return orderDate
  **/
  @ApiModelProperty(value = "")
  public String getOrderDate() {
    return orderDate;
  }

  public void setOrderDate(String orderDate) {
    this.orderDate = orderDate;
  }

  public ReturnItem createdDate(String createdDate) {
    this.createdDate = createdDate;
    return this;
  }

   /**
   * Get createdDate
   * @return createdDate
  **/
  @ApiModelProperty(value = "")
  public String getCreatedDate() {
    return createdDate;
  }

  public void setCreatedDate(String createdDate) {
    this.createdDate = createdDate;
  }

  public ReturnItem courierName(String courierName) {
    this.courierName = courierName;
    return this;
  }

   /**
   * Get courierName
   * @return courierName
  **/
  @ApiModelProperty(value = "")
  public String getCourierName() {
    return courierName;
  }

  public void setCourierName(String courierName) {
    this.courierName = courierName;
  }

  public ReturnItem sellerId(String sellerId) {
    this.sellerId = sellerId;
    return this;
  }

   /**
   * Get sellerId
   * @return sellerId
  **/
  @ApiModelProperty(value = "")
  public String getSellerId() {
    return sellerId;
  }

  public void setSellerId(String sellerId) {
    this.sellerId = sellerId;
  }

  public ReturnItem returnId(String returnId) {
    this.returnId = returnId;
    return this;
  }

   /**
   * Get returnId
   * @return returnId
  **/
  @ApiModelProperty(value = "")
  public String getReturnId() {
    return returnId;
  }

  public void setReturnId(String returnId) {
    this.returnId = returnId;
  }

  public ReturnItem status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public ReturnItem type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(value = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public ReturnItem reason(String reason) {
    this.reason = reason;
    return this;
  }

   /**
   * Get reason
   * @return reason
  **/
  @ApiModelProperty(value = "")
  public String getReason() {
    return reason;
  }

  public void setReason(String reason) {
    this.reason = reason;
  }

  public ReturnItem subReason(String subReason) {
    this.subReason = subReason;
    return this;
  }

   /**
   * Get subReason
   * @return subReason
  **/
  @ApiModelProperty(value = "")
  public String getSubReason() {
    return subReason;
  }

  public void setSubReason(String subReason) {
    this.subReason = subReason;
  }

  public ReturnItem trackingId(String trackingId) {
    this.trackingId = trackingId;
    return this;
  }

   /**
   * Get trackingId
   * @return trackingId
  **/
  @ApiModelProperty(value = "")
  public String getTrackingId() {
    return trackingId;
  }

  public void setTrackingId(String trackingId) {
    this.trackingId = trackingId;
  }

  public ReturnItem shipmentStatus(String shipmentStatus) {
    this.shipmentStatus = shipmentStatus;
    return this;
  }

   /**
   * Get shipmentStatus
   * @return shipmentStatus
  **/
  @ApiModelProperty(value = "")
  public String getShipmentStatus() {
    return shipmentStatus;
  }

  public void setShipmentStatus(String shipmentStatus) {
    this.shipmentStatus = shipmentStatus;
  }

  public ReturnItem shipmentId(String shipmentId) {
    this.shipmentId = shipmentId;
    return this;
  }

   /**
   * Get shipmentId
   * @return shipmentId
  **/
  @ApiModelProperty(value = "")
  public String getShipmentId() {
    return shipmentId;
  }

  public void setShipmentId(String shipmentId) {
    this.shipmentId = shipmentId;
  }

  public ReturnItem comments(String comments) {
    this.comments = comments;
    return this;
  }

   /**
   * Get comments
   * @return comments
  **/
  @ApiModelProperty(value = "")
  public String getComments() {
    return comments;
  }

  public void setComments(String comments) {
    this.comments = comments;
  }

  public ReturnItem updatedDate(String updatedDate) {
    this.updatedDate = updatedDate;
    return this;
  }

   /**
   * Get updatedDate
   * @return updatedDate
  **/
  @ApiModelProperty(value = "")
  public String getUpdatedDate() {
    return updatedDate;
  }

  public void setUpdatedDate(String updatedDate) {
    this.updatedDate = updatedDate;
  }

  public ReturnItem approvedOn(String approvedOn) {
    this.approvedOn = approvedOn;
    return this;
  }

   /**
   * Get approvedOn
   * @return approvedOn
  **/
  @ApiModelProperty(value = "")
  public String getApprovedOn() {
    return approvedOn;
  }

  public void setApprovedOn(String approvedOn) {
    this.approvedOn = approvedOn;
  }

  public ReturnItem expectedDate(String expectedDate) {
    this.expectedDate = expectedDate;
    return this;
  }

   /**
   * Get expectedDate
   * @return expectedDate
  **/
  @ApiModelProperty(value = "")
  public String getExpectedDate() {
    return expectedDate;
  }

  public void setExpectedDate(String expectedDate) {
    this.expectedDate = expectedDate;
  }

  public ReturnItem serviceProfile(ServiceProfileEnum serviceProfile) {
    this.serviceProfile = serviceProfile;
    return this;
  }

   /**
   * Get serviceProfile
   * @return serviceProfile
  **/
  @ApiModelProperty(value = "")
  public ServiceProfileEnum getServiceProfile() {
    return serviceProfile;
  }

  public void setServiceProfile(ServiceProfileEnum serviceProfile) {
    this.serviceProfile = serviceProfile;
  }

  public ReturnItem services(List<Service> services) {
    this.services = services;
    return this;
  }

  public ReturnItem addServicesItem(Service servicesItem) {
    if (this.services == null) {
      this.services = new ArrayList<Service>();
    }
    this.services.add(servicesItem);
    return this;
  }

   /**
   * Get services
   * @return services
  **/
  @ApiModelProperty(value = "")
  public List<Service> getServices() {
    return services;
  }

  public void setServices(List<Service> services) {
    this.services = services;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReturnItem returnItem = (ReturnItem) o;
    return Objects.equals(this.orderItemId, returnItem.orderItemId) &&
        Objects.equals(this.locationId, returnItem.locationId) &&
        Objects.equals(this.orderId, returnItem.orderId) &&
        Objects.equals(this.quantity, returnItem.quantity) &&
        Objects.equals(this.orderDate, returnItem.orderDate) &&
        Objects.equals(this.createdDate, returnItem.createdDate) &&
        Objects.equals(this.courierName, returnItem.courierName) &&
        Objects.equals(this.sellerId, returnItem.sellerId) &&
        Objects.equals(this.returnId, returnItem.returnId) &&
        Objects.equals(this.status, returnItem.status) &&
        Objects.equals(this.type, returnItem.type) &&
        Objects.equals(this.reason, returnItem.reason) &&
        Objects.equals(this.subReason, returnItem.subReason) &&
        Objects.equals(this.trackingId, returnItem.trackingId) &&
        Objects.equals(this.shipmentStatus, returnItem.shipmentStatus) &&
        Objects.equals(this.shipmentId, returnItem.shipmentId) &&
        Objects.equals(this.comments, returnItem.comments) &&
        Objects.equals(this.updatedDate, returnItem.updatedDate) &&
        Objects.equals(this.approvedOn, returnItem.approvedOn) &&
        Objects.equals(this.expectedDate, returnItem.expectedDate) &&
        Objects.equals(this.serviceProfile, returnItem.serviceProfile) &&
        Objects.equals(this.services, returnItem.services);
  }

  @Override
  public int hashCode() {
    return Objects.hash(orderItemId, locationId, orderId, quantity, orderDate, createdDate, courierName, sellerId, returnId, status, type, reason, subReason, trackingId, shipmentStatus, shipmentId, comments, updatedDate, approvedOn, expectedDate, serviceProfile, services);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReturnItem {\n");
    
    sb.append("    orderItemId: ").append(toIndentedString(orderItemId)).append("\n");
    sb.append("    locationId: ").append(toIndentedString(locationId)).append("\n");
    sb.append("    orderId: ").append(toIndentedString(orderId)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    orderDate: ").append(toIndentedString(orderDate)).append("\n");
    sb.append("    createdDate: ").append(toIndentedString(createdDate)).append("\n");
    sb.append("    courierName: ").append(toIndentedString(courierName)).append("\n");
    sb.append("    sellerId: ").append(toIndentedString(sellerId)).append("\n");
    sb.append("    returnId: ").append(toIndentedString(returnId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("    subReason: ").append(toIndentedString(subReason)).append("\n");
    sb.append("    trackingId: ").append(toIndentedString(trackingId)).append("\n");
    sb.append("    shipmentStatus: ").append(toIndentedString(shipmentStatus)).append("\n");
    sb.append("    shipmentId: ").append(toIndentedString(shipmentId)).append("\n");
    sb.append("    comments: ").append(toIndentedString(comments)).append("\n");
    sb.append("    updatedDate: ").append(toIndentedString(updatedDate)).append("\n");
    sb.append("    approvedOn: ").append(toIndentedString(approvedOn)).append("\n");
    sb.append("    expectedDate: ").append(toIndentedString(expectedDate)).append("\n");
    sb.append("    serviceProfile: ").append(toIndentedString(serviceProfile)).append("\n");
    sb.append("    services: ").append(toIndentedString(services)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

