/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.flipkart.api.seller.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.threeten.bp.OffsetDateTime;

/**
 * SelfShipReturnPickupRequest
 */

public class SelfShipReturnPickupRequest {
  @JsonProperty("returnId")
  private String returnId = null;

  @JsonProperty("pickupDate")
  private OffsetDateTime pickupDate = null;

  public SelfShipReturnPickupRequest returnId(String returnId) {
    this.returnId = returnId;
    return this;
  }

   /**
   * Get returnId
   * @return returnId
  **/
  @ApiModelProperty(value = "")
  public String getReturnId() {
    return returnId;
  }

  public void setReturnId(String returnId) {
    this.returnId = returnId;
  }

  public SelfShipReturnPickupRequest pickupDate(OffsetDateTime pickupDate) {
    this.pickupDate = pickupDate;
    return this;
  }

   /**
   * Get pickupDate
   * @return pickupDate
  **/
  @ApiModelProperty(required = true, value = "")
  public OffsetDateTime getPickupDate() {
    return pickupDate;
  }

  public void setPickupDate(OffsetDateTime pickupDate) {
    this.pickupDate = pickupDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SelfShipReturnPickupRequest selfShipReturnPickupRequest = (SelfShipReturnPickupRequest) o;
    return Objects.equals(this.returnId, selfShipReturnPickupRequest.returnId) &&
        Objects.equals(this.pickupDate, selfShipReturnPickupRequest.pickupDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(returnId, pickupDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SelfShipReturnPickupRequest {\n");
    
    sb.append("    returnId: ").append(toIndentedString(returnId)).append("\n");
    sb.append("    pickupDate: ").append(toIndentedString(pickupDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

