/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.flipkart.api.seller.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.flipkart.api.seller.client.model.Address;
import com.flipkart.api.seller.client.model.BuyerDetails;
import com.flipkart.api.seller.client.model.Courier;
import com.flipkart.api.seller.client.model.OrderItem;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * ShipmentDetails
 */

public class ShipmentDetails {
  @JsonProperty("orderId")
  private String orderId = null;

  @JsonProperty("shipmentId")
  private String shipmentId = null;

  @JsonProperty("orderItems")
  private List<OrderItem> orderItems = null;

  @JsonProperty("weighingRequired")
  private Boolean weighingRequired = null;

  @JsonProperty("deliveryAddress")
  private Address deliveryAddress = null;

  @JsonProperty("billingAddress")
  private Address billingAddress = null;

  @JsonProperty("buyerDetails")
  private BuyerDetails buyerDetails = null;

  @JsonProperty("sellerAddress")
  private Address sellerAddress = null;

  @JsonProperty("returnAddress")
  private Address returnAddress = null;

  @JsonProperty("courierDetails")
  private Courier courierDetails = null;

  public ShipmentDetails orderId(String orderId) {
    this.orderId = orderId;
    return this;
  }

   /**
   * Get orderId
   * @return orderId
  **/
  @ApiModelProperty(value = "")
  public String getOrderId() {
    return orderId;
  }

  public void setOrderId(String orderId) {
    this.orderId = orderId;
  }

  public ShipmentDetails shipmentId(String shipmentId) {
    this.shipmentId = shipmentId;
    return this;
  }

   /**
   * Get shipmentId
   * @return shipmentId
  **/
  @ApiModelProperty(value = "")
  public String getShipmentId() {
    return shipmentId;
  }

  public void setShipmentId(String shipmentId) {
    this.shipmentId = shipmentId;
  }

  public ShipmentDetails orderItems(List<OrderItem> orderItems) {
    this.orderItems = orderItems;
    return this;
  }

  public ShipmentDetails addOrderItemsItem(OrderItem orderItemsItem) {
    if (this.orderItems == null) {
      this.orderItems = new ArrayList<OrderItem>();
    }
    this.orderItems.add(orderItemsItem);
    return this;
  }

   /**
   * Get orderItems
   * @return orderItems
  **/
  @ApiModelProperty(value = "")
  public List<OrderItem> getOrderItems() {
    return orderItems;
  }

  public void setOrderItems(List<OrderItem> orderItems) {
    this.orderItems = orderItems;
  }

  public ShipmentDetails weighingRequired(Boolean weighingRequired) {
    this.weighingRequired = weighingRequired;
    return this;
  }

   /**
   * Get weighingRequired
   * @return weighingRequired
  **/
  @ApiModelProperty(value = "")
  public Boolean isWeighingRequired() {
    return weighingRequired;
  }

  public void setWeighingRequired(Boolean weighingRequired) {
    this.weighingRequired = weighingRequired;
  }

  public ShipmentDetails deliveryAddress(Address deliveryAddress) {
    this.deliveryAddress = deliveryAddress;
    return this;
  }

   /**
   * Get deliveryAddress
   * @return deliveryAddress
  **/
  @ApiModelProperty(value = "")
  public Address getDeliveryAddress() {
    return deliveryAddress;
  }

  public void setDeliveryAddress(Address deliveryAddress) {
    this.deliveryAddress = deliveryAddress;
  }

  public ShipmentDetails billingAddress(Address billingAddress) {
    this.billingAddress = billingAddress;
    return this;
  }

   /**
   * Get billingAddress
   * @return billingAddress
  **/
  @ApiModelProperty(value = "")
  public Address getBillingAddress() {
    return billingAddress;
  }

  public void setBillingAddress(Address billingAddress) {
    this.billingAddress = billingAddress;
  }

  public ShipmentDetails buyerDetails(BuyerDetails buyerDetails) {
    this.buyerDetails = buyerDetails;
    return this;
  }

   /**
   * Get buyerDetails
   * @return buyerDetails
  **/
  @ApiModelProperty(value = "")
  public BuyerDetails getBuyerDetails() {
    return buyerDetails;
  }

  public void setBuyerDetails(BuyerDetails buyerDetails) {
    this.buyerDetails = buyerDetails;
  }

  public ShipmentDetails sellerAddress(Address sellerAddress) {
    this.sellerAddress = sellerAddress;
    return this;
  }

   /**
   * Get sellerAddress
   * @return sellerAddress
  **/
  @ApiModelProperty(value = "")
  public Address getSellerAddress() {
    return sellerAddress;
  }

  public void setSellerAddress(Address sellerAddress) {
    this.sellerAddress = sellerAddress;
  }

  public ShipmentDetails returnAddress(Address returnAddress) {
    this.returnAddress = returnAddress;
    return this;
  }

   /**
   * Get returnAddress
   * @return returnAddress
  **/
  @ApiModelProperty(value = "")
  public Address getReturnAddress() {
    return returnAddress;
  }

  public void setReturnAddress(Address returnAddress) {
    this.returnAddress = returnAddress;
  }

  public ShipmentDetails courierDetails(Courier courierDetails) {
    this.courierDetails = courierDetails;
    return this;
  }

   /**
   * Get courierDetails
   * @return courierDetails
  **/
  @ApiModelProperty(value = "")
  public Courier getCourierDetails() {
    return courierDetails;
  }

  public void setCourierDetails(Courier courierDetails) {
    this.courierDetails = courierDetails;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShipmentDetails shipmentDetails = (ShipmentDetails) o;
    return Objects.equals(this.orderId, shipmentDetails.orderId) &&
        Objects.equals(this.shipmentId, shipmentDetails.shipmentId) &&
        Objects.equals(this.orderItems, shipmentDetails.orderItems) &&
        Objects.equals(this.weighingRequired, shipmentDetails.weighingRequired) &&
        Objects.equals(this.deliveryAddress, shipmentDetails.deliveryAddress) &&
        Objects.equals(this.billingAddress, shipmentDetails.billingAddress) &&
        Objects.equals(this.buyerDetails, shipmentDetails.buyerDetails) &&
        Objects.equals(this.sellerAddress, shipmentDetails.sellerAddress) &&
        Objects.equals(this.returnAddress, shipmentDetails.returnAddress) &&
        Objects.equals(this.courierDetails, shipmentDetails.courierDetails);
  }

  @Override
  public int hashCode() {
    return Objects.hash(orderId, shipmentId, orderItems, weighingRequired, deliveryAddress, billingAddress, buyerDetails, sellerAddress, returnAddress, courierDetails);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ShipmentDetails {\n");
    
    sb.append("    orderId: ").append(toIndentedString(orderId)).append("\n");
    sb.append("    shipmentId: ").append(toIndentedString(shipmentId)).append("\n");
    sb.append("    orderItems: ").append(toIndentedString(orderItems)).append("\n");
    sb.append("    weighingRequired: ").append(toIndentedString(weighingRequired)).append("\n");
    sb.append("    deliveryAddress: ").append(toIndentedString(deliveryAddress)).append("\n");
    sb.append("    billingAddress: ").append(toIndentedString(billingAddress)).append("\n");
    sb.append("    buyerDetails: ").append(toIndentedString(buyerDetails)).append("\n");
    sb.append("    sellerAddress: ").append(toIndentedString(sellerAddress)).append("\n");
    sb.append("    returnAddress: ").append(toIndentedString(returnAddress)).append("\n");
    sb.append("    courierDetails: ").append(toIndentedString(courierDetails)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

