/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.flipkart.api.seller.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.flipkart.api.seller.client.model.Form;
import com.flipkart.api.seller.client.model.OrderItem;
import com.flipkart.api.seller.client.model.SubShipment;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.OffsetDateTime;

/**
 * Shipment
 */

public class Shipment {
  @JsonProperty("shipmentId")
  private String shipmentId = null;

  @JsonProperty("dispatchByDate")
  private OffsetDateTime dispatchByDate = null;

  @JsonProperty("dispatchAfterDate")
  private OffsetDateTime dispatchAfterDate = null;

  @JsonProperty("updatedAt")
  private OffsetDateTime updatedAt = null;

  @JsonProperty("locationId")
  private String locationId = null;

  @JsonProperty("hold")
  private Boolean hold = null;

  @JsonProperty("mps")
  private Boolean mps = null;

  @JsonProperty("packagingPolicy")
  private String packagingPolicy = null;

  @JsonProperty("subShipments")
  private List<SubShipment> subShipments = null;

  @JsonProperty("orderItems")
  private List<OrderItem> orderItems = null;

  @JsonProperty("forms")
  private List<Form> forms = null;

  @JsonProperty("shipmentType")
  private String shipmentType = null;

  public Shipment shipmentId(String shipmentId) {
    this.shipmentId = shipmentId;
    return this;
  }

   /**
   * Get shipmentId
   * @return shipmentId
  **/
  @ApiModelProperty(value = "")
  public String getShipmentId() {
    return shipmentId;
  }

  public void setShipmentId(String shipmentId) {
    this.shipmentId = shipmentId;
  }

  public Shipment dispatchByDate(OffsetDateTime dispatchByDate) {
    this.dispatchByDate = dispatchByDate;
    return this;
  }

   /**
   * Get dispatchByDate
   * @return dispatchByDate
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getDispatchByDate() {
    return dispatchByDate;
  }

  public void setDispatchByDate(OffsetDateTime dispatchByDate) {
    this.dispatchByDate = dispatchByDate;
  }

  public Shipment dispatchAfterDate(OffsetDateTime dispatchAfterDate) {
    this.dispatchAfterDate = dispatchAfterDate;
    return this;
  }

   /**
   * Get dispatchAfterDate
   * @return dispatchAfterDate
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getDispatchAfterDate() {
    return dispatchAfterDate;
  }

  public void setDispatchAfterDate(OffsetDateTime dispatchAfterDate) {
    this.dispatchAfterDate = dispatchAfterDate;
  }

  public Shipment updatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }

  public Shipment locationId(String locationId) {
    this.locationId = locationId;
    return this;
  }

   /**
   * Get locationId
   * @return locationId
  **/
  @ApiModelProperty(value = "")
  public String getLocationId() {
    return locationId;
  }

  public void setLocationId(String locationId) {
    this.locationId = locationId;
  }

  public Shipment hold(Boolean hold) {
    this.hold = hold;
    return this;
  }

   /**
   * Get hold
   * @return hold
  **/
  @ApiModelProperty(value = "")
  public Boolean isHold() {
    return hold;
  }

  public void setHold(Boolean hold) {
    this.hold = hold;
  }

  public Shipment mps(Boolean mps) {
    this.mps = mps;
    return this;
  }

   /**
   * Get mps
   * @return mps
  **/
  @ApiModelProperty(value = "")
  public Boolean isMps() {
    return mps;
  }

  public void setMps(Boolean mps) {
    this.mps = mps;
  }

  public Shipment packagingPolicy(String packagingPolicy) {
    this.packagingPolicy = packagingPolicy;
    return this;
  }

   /**
   * Get packagingPolicy
   * @return packagingPolicy
  **/
  @ApiModelProperty(value = "")
  public String getPackagingPolicy() {
    return packagingPolicy;
  }

  public void setPackagingPolicy(String packagingPolicy) {
    this.packagingPolicy = packagingPolicy;
  }

  public Shipment subShipments(List<SubShipment> subShipments) {
    this.subShipments = subShipments;
    return this;
  }

  public Shipment addSubShipmentsItem(SubShipment subShipmentsItem) {
    if (this.subShipments == null) {
      this.subShipments = new ArrayList<SubShipment>();
    }
    this.subShipments.add(subShipmentsItem);
    return this;
  }

   /**
   * Get subShipments
   * @return subShipments
  **/
  @ApiModelProperty(value = "")
  public List<SubShipment> getSubShipments() {
    return subShipments;
  }

  public void setSubShipments(List<SubShipment> subShipments) {
    this.subShipments = subShipments;
  }

  public Shipment orderItems(List<OrderItem> orderItems) {
    this.orderItems = orderItems;
    return this;
  }

  public Shipment addOrderItemsItem(OrderItem orderItemsItem) {
    if (this.orderItems == null) {
      this.orderItems = new ArrayList<OrderItem>();
    }
    this.orderItems.add(orderItemsItem);
    return this;
  }

   /**
   * Get orderItems
   * @return orderItems
  **/
  @ApiModelProperty(value = "")
  public List<OrderItem> getOrderItems() {
    return orderItems;
  }

  public void setOrderItems(List<OrderItem> orderItems) {
    this.orderItems = orderItems;
  }

  public Shipment forms(List<Form> forms) {
    this.forms = forms;
    return this;
  }

  public Shipment addFormsItem(Form formsItem) {
    if (this.forms == null) {
      this.forms = new ArrayList<Form>();
    }
    this.forms.add(formsItem);
    return this;
  }

   /**
   * Get forms
   * @return forms
  **/
  @ApiModelProperty(value = "")
  public List<Form> getForms() {
    return forms;
  }

  public void setForms(List<Form> forms) {
    this.forms = forms;
  }

  public Shipment shipmentType(String shipmentType) {
    this.shipmentType = shipmentType;
    return this;
  }

   /**
   * Get shipmentType
   * @return shipmentType
  **/
  @ApiModelProperty(value = "")
  public String getShipmentType() {
    return shipmentType;
  }

  public void setShipmentType(String shipmentType) {
    this.shipmentType = shipmentType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Shipment shipment = (Shipment) o;
    return Objects.equals(this.shipmentId, shipment.shipmentId) &&
        Objects.equals(this.dispatchByDate, shipment.dispatchByDate) &&
        Objects.equals(this.dispatchAfterDate, shipment.dispatchAfterDate) &&
        Objects.equals(this.updatedAt, shipment.updatedAt) &&
        Objects.equals(this.locationId, shipment.locationId) &&
        Objects.equals(this.hold, shipment.hold) &&
        Objects.equals(this.mps, shipment.mps) &&
        Objects.equals(this.packagingPolicy, shipment.packagingPolicy) &&
        Objects.equals(this.subShipments, shipment.subShipments) &&
        Objects.equals(this.orderItems, shipment.orderItems) &&
        Objects.equals(this.forms, shipment.forms) &&
        Objects.equals(this.shipmentType, shipment.shipmentType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(shipmentId, dispatchByDate, dispatchAfterDate, updatedAt, locationId, hold, mps, packagingPolicy, subShipments, orderItems, forms, shipmentType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Shipment {\n");
    
    sb.append("    shipmentId: ").append(toIndentedString(shipmentId)).append("\n");
    sb.append("    dispatchByDate: ").append(toIndentedString(dispatchByDate)).append("\n");
    sb.append("    dispatchAfterDate: ").append(toIndentedString(dispatchAfterDate)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    locationId: ").append(toIndentedString(locationId)).append("\n");
    sb.append("    hold: ").append(toIndentedString(hold)).append("\n");
    sb.append("    mps: ").append(toIndentedString(mps)).append("\n");
    sb.append("    packagingPolicy: ").append(toIndentedString(packagingPolicy)).append("\n");
    sb.append("    subShipments: ").append(toIndentedString(subShipments)).append("\n");
    sb.append("    orderItems: ").append(toIndentedString(orderItems)).append("\n");
    sb.append("    forms: ").append(toIndentedString(forms)).append("\n");
    sb.append("    shipmentType: ").append(toIndentedString(shipmentType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

