/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.flipkart.api.seller.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.flipkart.api.seller.client.model.ModelPackage;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * SubShipment
 */

public class SubShipment {
  @JsonProperty("subShipmentId")
  private String subShipmentId = null;

  @JsonProperty("packages")
  private List<ModelPackage> packages = null;

  public SubShipment subShipmentId(String subShipmentId) {
    this.subShipmentId = subShipmentId;
    return this;
  }

   /**
   * Get subShipmentId
   * @return subShipmentId
  **/
  @ApiModelProperty(value = "")
  public String getSubShipmentId() {
    return subShipmentId;
  }

  public void setSubShipmentId(String subShipmentId) {
    this.subShipmentId = subShipmentId;
  }

  public SubShipment packages(List<ModelPackage> packages) {
    this.packages = packages;
    return this;
  }

  public SubShipment addPackagesItem(ModelPackage packagesItem) {
    if (this.packages == null) {
      this.packages = new ArrayList<ModelPackage>();
    }
    this.packages.add(packagesItem);
    return this;
  }

   /**
   * Get packages
   * @return packages
  **/
  @ApiModelProperty(value = "")
  public List<ModelPackage> getPackages() {
    return packages;
  }

  public void setPackages(List<ModelPackage> packages) {
    this.packages = packages;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubShipment subShipment = (SubShipment) o;
    return Objects.equals(this.subShipmentId, subShipment.subShipmentId) &&
        Objects.equals(this.packages, subShipment.packages);
  }

  @Override
  public int hashCode() {
    return Objects.hash(subShipmentId, packages);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubShipment {\n");
    
    sb.append("    subShipmentId: ").append(toIndentedString(subShipmentId)).append("\n");
    sb.append("    packages: ").append(toIndentedString(packages)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

