/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.flipkart.api.seller.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;

/**
 * TaxDetails
 */

public class TaxDetails {
  @JsonProperty("cgstRate")
  private BigDecimal cgstRate = null;

  @JsonProperty("sgstRate")
  private BigDecimal sgstRate = null;

  @JsonProperty("igstRate")
  private BigDecimal igstRate = null;

  public TaxDetails cgstRate(BigDecimal cgstRate) {
    this.cgstRate = cgstRate;
    return this;
  }

   /**
   * Get cgstRate
   * @return cgstRate
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getCgstRate() {
    return cgstRate;
  }

  public void setCgstRate(BigDecimal cgstRate) {
    this.cgstRate = cgstRate;
  }

  public TaxDetails sgstRate(BigDecimal sgstRate) {
    this.sgstRate = sgstRate;
    return this;
  }

   /**
   * Get sgstRate
   * @return sgstRate
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getSgstRate() {
    return sgstRate;
  }

  public void setSgstRate(BigDecimal sgstRate) {
    this.sgstRate = sgstRate;
  }

  public TaxDetails igstRate(BigDecimal igstRate) {
    this.igstRate = igstRate;
    return this;
  }

   /**
   * Get igstRate
   * @return igstRate
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getIgstRate() {
    return igstRate;
  }

  public void setIgstRate(BigDecimal igstRate) {
    this.igstRate = igstRate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TaxDetails taxDetails = (TaxDetails) o;
    return Objects.equals(this.cgstRate, taxDetails.cgstRate) &&
        Objects.equals(this.sgstRate, taxDetails.sgstRate) &&
        Objects.equals(this.igstRate, taxDetails.igstRate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cgstRate, sgstRate, igstRate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TaxDetails {\n");
    
    sb.append("    cgstRate: ").append(toIndentedString(cgstRate)).append("\n");
    sb.append("    sgstRate: ").append(toIndentedString(sgstRate)).append("\n");
    sb.append("    igstRate: ").append(toIndentedString(igstRate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

