/*
 * listings-hyperlocal-v3
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.flipkart.api.seller.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.flipkart.api.seller.client.model.AddressLabel;
import com.flipkart.api.seller.client.model.DatingLabel;
import com.flipkart.api.seller.client.model.Location;
import com.flipkart.api.seller.client.model.ModelPackage;
import com.flipkart.api.seller.client.model.Price;
import com.flipkart.api.seller.client.model.Tax;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.flipkart.api.seller.client.JSON;


/**
 * UpdateHyperlocalListingRequest
 */
@JsonPropertyOrder({
    UpdateHyperlocalListingRequest.JSON_PROPERTY_PRODUCT_ID,
    UpdateHyperlocalListingRequest.JSON_PROPERTY_PRICE,
    UpdateHyperlocalListingRequest.JSON_PROPERTY_TAX,
    UpdateHyperlocalListingRequest.JSON_PROPERTY_LISTING_STATUS,
    UpdateHyperlocalListingRequest.JSON_PROPERTY_PACKAGE,
    UpdateHyperlocalListingRequest.JSON_PROPERTY_LOCATION,
    UpdateHyperlocalListingRequest.JSON_PROPERTY_ADDRESS_LABEL,
    UpdateHyperlocalListingRequest.JSON_PROPERTY_DATING_LABEL,
    UpdateHyperlocalListingRequest.JSON_PROPERTY_ARCHIVED_STATUS
})

public class UpdateHyperlocalListingRequest {
  public static final String JSON_PROPERTY_PRODUCT_ID = "product_id";
  private String productId;

  public static final String JSON_PROPERTY_PRICE = "price";
  private Price price;

  public static final String JSON_PROPERTY_TAX = "tax";
  private Tax tax;

  /**
   * Gets or Sets listingStatus
   */
  public enum ListingStatusEnum {
    ACTIVE("ACTIVE"),

    INACTIVE("INACTIVE");

    private String value;

    ListingStatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ListingStatusEnum fromValue(String value) {
      for (ListingStatusEnum b : ListingStatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_LISTING_STATUS = "listing_status";
  private ListingStatusEnum listingStatus;

  public static final String JSON_PROPERTY_PACKAGE = "package";
  private ModelPackage _package;

  public static final String JSON_PROPERTY_LOCATION = "location";
  private Location location;

  public static final String JSON_PROPERTY_ADDRESS_LABEL = "address_label";
  private AddressLabel addressLabel;

  public static final String JSON_PROPERTY_DATING_LABEL = "dating_label";
  private DatingLabel datingLabel;

  /**
   * Gets or Sets archivedStatus
   */
  public enum ArchivedStatusEnum {
    ARCHIVED("ARCHIVED"),

    NONE("NONE");

    private String value;

    ArchivedStatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ArchivedStatusEnum fromValue(String value) {
      for (ArchivedStatusEnum b : ArchivedStatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_ARCHIVED_STATUS = "archived_status";
  private ArchivedStatusEnum archivedStatus;

  public UpdateHyperlocalListingRequest() {
  }

  public UpdateHyperlocalListingRequest productId(String productId) {
    this.productId = productId;
    return this;
  }

  /**
   * Get productId
   * @return productId
   **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_PRODUCT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getProductId() {
    return productId;
  }


  @JsonProperty(JSON_PROPERTY_PRODUCT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProductId(String productId) {
    this.productId = productId;
  }


  public UpdateHyperlocalListingRequest price(Price price) {
    this.price = price;
    return this;
  }

  /**
   * Get price
   * @return price
   **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_PRICE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Price getPrice() {
    return price;
  }


  @JsonProperty(JSON_PROPERTY_PRICE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPrice(Price price) {
    this.price = price;
  }


  public UpdateHyperlocalListingRequest tax(Tax tax) {
    this.tax = tax;
    return this;
  }

  /**
   * Get tax
   * @return tax
   **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_TAX)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Tax getTax() {
    return tax;
  }


  @JsonProperty(JSON_PROPERTY_TAX)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTax(Tax tax) {
    this.tax = tax;
  }


  public UpdateHyperlocalListingRequest listingStatus(ListingStatusEnum listingStatus) {
    this.listingStatus = listingStatus;
    return this;
  }

  /**
   * Get listingStatus
   * @return listingStatus
   **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_LISTING_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ListingStatusEnum getListingStatus() {
    return listingStatus;
  }


  @JsonProperty(JSON_PROPERTY_LISTING_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setListingStatus(ListingStatusEnum listingStatus) {
    this.listingStatus = listingStatus;
  }


  public UpdateHyperlocalListingRequest _package(ModelPackage _package) {
    this._package = _package;
    return this;
  }

  /**
   * Get _package
   * @return _package
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PACKAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ModelPackage getPackage() {
    return _package;
  }


  @JsonProperty(JSON_PROPERTY_PACKAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPackage(ModelPackage _package) {
    this._package = _package;
  }


  public UpdateHyperlocalListingRequest location(Location location) {
    this.location = location;
    return this;
  }

  /**
   * Get location
   * @return location
   **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_LOCATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Location getLocation() {
    return location;
  }


  @JsonProperty(JSON_PROPERTY_LOCATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLocation(Location location) {
    this.location = location;
  }


  public UpdateHyperlocalListingRequest addressLabel(AddressLabel addressLabel) {
    this.addressLabel = addressLabel;
    return this;
  }

  /**
   * Get addressLabel
   * @return addressLabel
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ADDRESS_LABEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AddressLabel getAddressLabel() {
    return addressLabel;
  }


  @JsonProperty(JSON_PROPERTY_ADDRESS_LABEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAddressLabel(AddressLabel addressLabel) {
    this.addressLabel = addressLabel;
  }


  public UpdateHyperlocalListingRequest datingLabel(DatingLabel datingLabel) {
    this.datingLabel = datingLabel;
    return this;
  }

  /**
   * Get datingLabel
   * @return datingLabel
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DATING_LABEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DatingLabel getDatingLabel() {
    return datingLabel;
  }


  @JsonProperty(JSON_PROPERTY_DATING_LABEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDatingLabel(DatingLabel datingLabel) {
    this.datingLabel = datingLabel;
  }


  public UpdateHyperlocalListingRequest archivedStatus(ArchivedStatusEnum archivedStatus) {
    this.archivedStatus = archivedStatus;
    return this;
  }

  /**
   * Get archivedStatus
   * @return archivedStatus
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ARCHIVED_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ArchivedStatusEnum getArchivedStatus() {
    return archivedStatus;
  }


  @JsonProperty(JSON_PROPERTY_ARCHIVED_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setArchivedStatus(ArchivedStatusEnum archivedStatus) {
    this.archivedStatus = archivedStatus;
  }


  /**
   * Return true if this UpdateHyperlocalListingRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateHyperlocalListingRequest updateHyperlocalListingRequest = (UpdateHyperlocalListingRequest) o;
    return Objects.equals(this.productId, updateHyperlocalListingRequest.productId) &&
        Objects.equals(this.price, updateHyperlocalListingRequest.price) &&
        Objects.equals(this.tax, updateHyperlocalListingRequest.tax) &&
        Objects.equals(this.listingStatus, updateHyperlocalListingRequest.listingStatus) &&
        Objects.equals(this._package, updateHyperlocalListingRequest._package) &&
        Objects.equals(this.location, updateHyperlocalListingRequest.location) &&
        Objects.equals(this.addressLabel, updateHyperlocalListingRequest.addressLabel) &&
        Objects.equals(this.datingLabel, updateHyperlocalListingRequest.datingLabel) &&
        Objects.equals(this.archivedStatus, updateHyperlocalListingRequest.archivedStatus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(productId, price, tax, listingStatus, _package, location, addressLabel, datingLabel, archivedStatus);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateHyperlocalListingRequest {\n");
    sb.append("    productId: ").append(toIndentedString(productId)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    tax: ").append(toIndentedString(tax)).append("\n");
    sb.append("    listingStatus: ").append(toIndentedString(listingStatus)).append("\n");
    sb.append("    _package: ").append(toIndentedString(_package)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    addressLabel: ").append(toIndentedString(addressLabel)).append("\n");
    sb.append("    datingLabel: ").append(toIndentedString(datingLabel)).append("\n");
    sb.append("    archivedStatus: ").append(toIndentedString(archivedStatus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

