/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.flipkart.api.seller.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.flipkart.api.seller.client.model.Otc;
import com.flipkart.api.seller.client.model.PickUpDate;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * VendorGroupCodeDetailsResponseV3
 */

public class VendorGroupCodeDetailsResponseV3 {
  @JsonProperty("vendorGroupCode")
  private String vendorGroupCode = null;

  @JsonProperty("count")
  private Integer count = null;

  @JsonProperty("pickUpDate")
  private PickUpDate pickUpDate = null;

  @JsonProperty("otc")
  private Otc otc = null;

  @JsonProperty("isMps")
  private Boolean isMps = null;

  public VendorGroupCodeDetailsResponseV3 vendorGroupCode(String vendorGroupCode) {
    this.vendorGroupCode = vendorGroupCode;
    return this;
  }

   /**
   * Get vendorGroupCode
   * @return vendorGroupCode
  **/
  @ApiModelProperty(value = "")
  public String getVendorGroupCode() {
    return vendorGroupCode;
  }

  public void setVendorGroupCode(String vendorGroupCode) {
    this.vendorGroupCode = vendorGroupCode;
  }

  public VendorGroupCodeDetailsResponseV3 count(Integer count) {
    this.count = count;
    return this;
  }

   /**
   * Get count
   * @return count
  **/
  @ApiModelProperty(value = "")
  public Integer getCount() {
    return count;
  }

  public void setCount(Integer count) {
    this.count = count;
  }

  public VendorGroupCodeDetailsResponseV3 pickUpDate(PickUpDate pickUpDate) {
    this.pickUpDate = pickUpDate;
    return this;
  }

   /**
   * Get pickUpDate
   * @return pickUpDate
  **/
  @ApiModelProperty(value = "")
  public PickUpDate getPickUpDate() {
    return pickUpDate;
  }

  public void setPickUpDate(PickUpDate pickUpDate) {
    this.pickUpDate = pickUpDate;
  }

  public VendorGroupCodeDetailsResponseV3 otc(Otc otc) {
    this.otc = otc;
    return this;
  }

   /**
   * Get otc
   * @return otc
  **/
  @ApiModelProperty(value = "")
  public Otc getOtc() {
    return otc;
  }

  public void setOtc(Otc otc) {
    this.otc = otc;
  }

  public VendorGroupCodeDetailsResponseV3 isMps(Boolean isMps) {
    this.isMps = isMps;
    return this;
  }

   /**
   * Get isMps
   * @return isMps
  **/
  @ApiModelProperty(value = "")
  public Boolean isIsMps() {
    return isMps;
  }

  public void setIsMps(Boolean isMps) {
    this.isMps = isMps;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VendorGroupCodeDetailsResponseV3 vendorGroupCodeDetailsResponseV3 = (VendorGroupCodeDetailsResponseV3) o;
    return Objects.equals(this.vendorGroupCode, vendorGroupCodeDetailsResponseV3.vendorGroupCode) &&
        Objects.equals(this.count, vendorGroupCodeDetailsResponseV3.count) &&
        Objects.equals(this.pickUpDate, vendorGroupCodeDetailsResponseV3.pickUpDate) &&
        Objects.equals(this.otc, vendorGroupCodeDetailsResponseV3.otc) &&
        Objects.equals(this.isMps, vendorGroupCodeDetailsResponseV3.isMps);
  }

  @Override
  public int hashCode() {
    return Objects.hash(vendorGroupCode, count, pickUpDate, otc, isMps);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VendorGroupCodeDetailsResponseV3 {\n");
    
    sb.append("    vendorGroupCode: ").append(toIndentedString(vendorGroupCode)).append("\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    pickUpDate: ").append(toIndentedString(pickUpDate)).append("\n");
    sb.append("    otc: ").append(toIndentedString(otc)).append("\n");
    sb.append("    isMps: ").append(toIndentedString(isMps)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

